import { ArrowLeft, BriefcaseBusiness, Clock3, Info, Plane, RotateCcw, ShieldCheck, Star } from 'lucide-react';
import type { FlightResult } from '@/types/flight';
import { formatDuration, formatPersianNumber, formatPrice, formatTime } from '@/utils/flight';

interface Props { flight: FlightResult; onDetails: () => void; onSelect: (flight: FlightResult) => void; selected?: boolean; }
const FlightCard = ({ flight, onDetails, onSelect, selected }: Props) => <article className={`rounded-2xl border bg-card p-4 transition hover:border-secondary hover:shadow-md sm:p-5 ${selected ? 'border-primary ring-2 ring-primary/15' : 'border-border'}`}>
  <div className="flex flex-wrap items-start justify-between gap-3 border-b border-border pb-4"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-secondary/10 text-sm font-extrabold text-secondary">{flight.airlineCode}</span><div><p className="font-bold">{flight.airlineName}</p><p className="text-xs text-muted-foreground">{flight.flightNumber} · {flight.aircraft}</p></div></div><div className="flex flex-wrap gap-1.5">{flight.kind && <span className="rounded-md bg-muted px-2 py-1 text-[11px] font-medium">{flight.kind}</span>}{flight.seatsLeft && <span className="rounded-md bg-warning/10 px-2 py-1 text-[11px] font-semibold text-warning">تنها {flight.seatsLeft} صندلی</span>}{flight.tags.map((tag) => <span key={tag} className="rounded-md bg-primary/10 px-2 py-1 text-[11px] font-semibold text-primary">{tag}</span>)}</div></div>
  <div className="grid gap-5 py-5 md:grid-cols-[1fr_auto_1fr] md:items-center"><div className="flex items-center justify-between gap-3 md:block"><div><p className="text-2xl font-extrabold tracking-tight">{formatTime(flight.departure)}</p><p className="mt-1 text-sm font-semibold">{flight.fromCity} <span className="text-xs text-muted-foreground">({flight.fromCode})</span></p></div><div className="md:hidden"><ArrowLeft className="size-5 rotate-[-90deg] text-muted-foreground" /></div></div><div className="hidden text-center md:block"><p className="text-xs text-muted-foreground">{formatDuration(flight.durationMinutes)}</p><div className="relative my-2 flex items-center gap-2"><span className="size-2 rounded-full border-2 border-secondary bg-card" /><span className="h-px flex-1 bg-border" /><Plane className="size-4 rotate-[-90deg] text-secondary" /><span className="h-px flex-1 bg-border" /><span className="size-2 rounded-full bg-secondary" /></div><p className={`text-xs font-semibold ${flight.stops ? 'text-warning' : 'text-secondary'}`}>{flight.stops ? `${flight.stops} توقف · ${flight.stopCity}` : 'مستقیم'}</p></div><div className="flex items-center justify-between gap-3 text-end md:block"><div><p className="text-2xl font-extrabold tracking-tight">{formatTime(flight.arrival)}</p><p className="mt-1 text-sm font-semibold">{flight.toCity} <span className="text-xs text-muted-foreground">({flight.toCode})</span></p></div><div className="mt-2 text-xs text-muted-foreground md:hidden">{formatDuration(flight.durationMinutes)} · {flight.stops ? `${flight.stops} توقف` : 'مستقیم'}</div></div></div>
  <div className="flex flex-wrap items-center gap-x-4 gap-y-2 border-t border-border pt-3 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><BriefcaseBusiness className="size-3.5 text-secondary" /> بار {flight.baggageKg} کیلو</span><span className="inline-flex items-center gap-1"><ShieldCheck className="size-3.5 text-secondary" /> {flight.refundable ? 'قابل استرداد' : 'غیرقابل استرداد'}</span><span className="inline-flex items-center gap-1"><Clock3 className="size-3.5" /> {flight.cabin}</span><button type="button" onClick={onDetails} className="ms-auto inline-flex min-h-8 items-center gap-1 font-semibold text-secondary hover:text-primary"><Info className="size-3.5" /> جزئیات پرواز</button></div>
  <div className="mt-4 flex flex-col gap-3 rounded-xl bg-muted/60 p-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-xs text-muted-foreground">برای هر بزرگسال</p><p className="text-xl font-extrabold text-primary">{formatPrice(flight.price)}</p>{flight.originalPrice && <p className="text-xs text-muted-foreground line-through">{formatPersianNumber(flight.originalPrice)} تومان</p>}</div><button type="button" onClick={() => onSelect(flight)} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-lg bg-primary px-5 text-sm font-bold text-primary-foreground hover:bg-primary/90">{selected ? 'انتخاب شد' : 'انتخاب پرواز'} <ArrowLeft className="size-4" /></button></div>
</article>;
export default FlightCard;
