"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { operationalStatusLabel } from "./status-presentation";

type Row=Record<string,unknown>;
const labels:Record<string,string>={todayArrivalIssues:"ورود امروز نیازمند بررسی",manualReview:"رزرو نیازمند اقدام",providerBookingUnknown:"نتیجه نامعلوم تأمین‌کننده",reconciliationIssues:"اختلاف تطبیق",visaNeedsReview:"ویزای منتظر بررسی",refundRequested:"استرداد در انتظار",supportWaiting:"پشتیبانی منتظر پاسخ",settlementReady:"تسویه آماده",onboardingPending:"پذیرش ناقص",settlementUpdates:"تغییر تسویه",profileTeamIssues:"نقص پروفایل یا تیم",lowAvailability:"موجودی کم یا صفر"};
const allPaths:Record<string,string>={todayArrivalIssues:"hotel-bookings",manualReview:"orders",providerBookingUnknown:"orders",reconciliationIssues:"providers",visaNeedsReview:"visa",refundRequested:"refunds",supportWaiting:"support",settlementReady:"finance",onboardingPending:"merchants",settlementUpdates:"settlements",profileTeamIssues:"profile",lowAvailability:"inventory"};
function nested(row:Row,path:string){return path.split(".").reduce<unknown>((value,key)=>value&&typeof value==="object"?(value as Row)[key]:undefined,row)}
function rowTitle(row:Row){return String(row.orderNumber??row.subject??row.name??row.country??nested(row,"order.orderNumber")??nested(row,"ratePlan.roomType.property.name")??"مورد عملیاتی")}
function context(row:Row){const values=[row.status,nested(row,"order.serviceType"),row.provider,nested(row,"ratePlan.roomType.name"),row.availableRooms].filter(value=>value!==undefined&&value!==null).map(operationalStatusLabel);return values.join(" · ")||"برای بررسی و اقدام باز کنید"}
function detailHref(scope:string,key:string,row:Row){const base=`/${scope}/${allPaths[key]??""}`;if(["supportWaiting","visaNeedsReview","onboardingPending"].includes(key)&&row.id)return `${base}/${row.id}`;if(["manualReview","todayArrivalIssues"].includes(key)&&row.id)return `/${scope}/orders/${row.id}`;if(key==="providerBookingUnknown"&&nested(row,"order.id"))return `/${scope}/orders/${nested(row,"order.id")}`;return base}

export default function ActionQueue({scope}:{scope:"backoffice"|"merchant"}){
  const[queue,setQueue]=useState<Record<string,Row[]>|null>(null);const[error,setError]=useState("");
  useEffect(()=>{fetch(`/api/${scope}/action-required`,{credentials:"include",cache:"no-store"}).then(async response=>{const body=await response.json();if(!response.ok)throw new Error(body.error?.message??"صف عملیات دریافت نشد");setQueue(body.queue??{})}).catch(reason=>setError(reason.message))},[scope]);
  if(!queue&&!error)return null;const visible=Object.entries(queue??{}).filter(([,rows])=>rows.length);
  return <section className="mt-5 rounded-3xl border bg-white p-5 shadow-sm"><div><h2 className="text-xl font-black">نیازمند اقدام</h2><p className="mt-1 text-sm text-slate-500">موارد واقعی با مسیر مستقیم به صفحه عملیات.</p></div>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="mt-4 grid gap-4 lg:grid-cols-2">{visible.map(([key,rows])=><article key={key} className="rounded-2xl border border-red-100 bg-red-50/40 p-4"><div className="flex items-center justify-between gap-3"><h3 className="text-sm font-black">{labels[key]??key}</h3><span className="rounded-full bg-white px-2 py-1 text-xs font-black text-primary">{rows.length.toLocaleString("fa-IR")}</span></div><div className="mt-3 space-y-2">{rows.slice(0,3).map((row,index)=><Link key={String(row.id??index)} href={detailHref(scope,key,row)} className="block rounded-xl border bg-white p-3 transition hover:border-red-200"><b className="text-sm">{rowTitle(row)}</b><p className="mt-1 text-xs text-slate-500">{context(row)}</p></Link>)}</div>{rows.length>3&&<Link href={`/${scope}/${allPaths[key]??""}`} className="mt-3 inline-block text-xs font-bold text-primary">مشاهده همه {rows.length.toLocaleString("fa-IR")} مورد</Link>}</article>)}{visible.length===0&&<p className="text-sm text-slate-500">مورد بازی در صف نیست.</p>}</div></section>;
}
