"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { operationalStatusLabel } from "./status-presentation";

type Kind="refunds"|"support";
type CaseRow={id:string;status:string;amount?:number;destination?:string;reason?:string;subject?:string;category?:string;order?:{orderNumber?:string};organization?:{name?:string}};
const supportTransitions:Record<string,string[]>={open:["pending","resolved","closed"],pending:["open","resolved","closed"],resolved:["open","closed"],closed:["open"]};

export default function CaseQueues({kind}:{kind:Kind}){
  const[rows,setRows]=useState<CaseRow[]>([]);const[error,setError]=useState("");const[saving,setSaving]=useState<string|null>(null);const[page,setPage]=useState(1);const[total,setTotal]=useState(0);
  const load=useCallback(async()=>{setError("");try{const query=kind==="refunds"?`preset=30d&page=${page}&perPage=20`:`page=${page}&perPage=20`;const response=await fetch(`/api/backoffice/${kind}?${query}`,{credentials:"include",cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error?.message??"صف دریافت نشد");setRows(body[kind]??body.tickets??[]);setTotal(body.pagination?.total??0)}catch(reason){setError(reason instanceof Error?reason.message:"خطای ناشناخته")}},[kind,page]);
  useEffect(()=>{void load()},[load]);
  const update=async(row:CaseRow,status:string)=>{const warning=kind==="refunds"?(status==="failed"?"شکست عملیات استرداد ثبت شود؟ این اقدام در ممیزی ذخیره می‌شود.":"پردازش استرداد آغاز شود؟"):`وضعیت درخواست به «${operationalStatusLabel(status)}» تغییر کند؟`;if(!window.confirm(warning))return;setSaving(row.id);const body=kind==="refunds"?{status,reason:status==="failed"?"نیازمند بررسی و اصلاح عملیات استرداد":"در حال پردازش توسط عملیات"}:{status};const response=await fetch(`/api/backoffice/${kind}/${row.id}`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const payload=await response.json();setSaving(null);if(!response.ok){setError(payload.error?.message??"عملیات ناموفق بود");return}await load()};
  const pages=Math.max(1,Math.ceil(total/20));
  return <section className="rounded-3xl border bg-white p-5"><h1 className="text-xl font-black">{kind==="refunds"?"صف استرداد":"عملیات پشتیبانی"}</h1><p className="mt-1 text-sm text-slate-500">فقط انتقال‌های مجاز API اجرا می‌شوند و اقدامات حساس تأیید می‌خواهند.</p>{error&&<p role="alert" className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="mt-5 space-y-3">{rows.map(row=><article key={row.id} className="flex flex-col justify-between gap-3 rounded-2xl border p-4 md:flex-row md:items-center"><div><b>{kind==="refunds"?row.order?.orderNumber:row.subject}</b><p className="mt-1 text-xs text-slate-500">{kind==="refunds"?`${(row.amount??0).toLocaleString("fa-IR")} تومان · ${row.destination??"—"} · ${row.reason??"—"}`:`${row.category??"عمومی"} · ${row.organization?.name??"مشتری"}`} · {operationalStatusLabel(row.status)}</p></div><div className="flex flex-wrap gap-2">{kind==="support"&&<Link href={`/backoffice/support/${row.id}`} className="rounded-lg border border-red-200 px-3 py-2 text-xs font-bold text-primary">مشاهده جزئیات</Link>}{kind==="refunds"?<><button disabled={saving===row.id||row.status==="processing"} onClick={()=>void update(row,"processing")} className="rounded-lg bg-primary px-3 py-2 text-xs font-bold text-white disabled:opacity-40">شروع پردازش</button><button disabled={saving===row.id} onClick={()=>void update(row,"failed")} className="rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-40">ثبت شکست</button></>:(supportTransitions[row.status]??[]).map(status=><button key={status} disabled={saving===row.id} onClick={()=>void update(row,status)} className="rounded-lg border px-3 py-2 text-xs font-bold disabled:opacity-40">{operationalStatusLabel(status)}</button>)}</div></article>)}{!rows.length&&<p className="py-12 text-center text-sm text-slate-500">موردی در صف نیست.</p>}</div>{pages>1&&<nav aria-label="صفحه‌بندی صف" className="mt-5 flex items-center justify-between border-t pt-4"><button disabled={page<=1} onClick={()=>setPage(value=>value-1)} className="rounded-lg border px-4 py-2 text-xs font-bold disabled:opacity-40">صفحه قبل</button><span className="text-xs text-slate-500">صفحه {page.toLocaleString("fa-IR")} از {pages.toLocaleString("fa-IR")}</span><button disabled={page>=pages} onClick={()=>setPage(value=>value+1)} className="rounded-lg border px-4 py-2 text-xs font-bold disabled:opacity-40">صفحه بعد</button></nav>}</section>;
}
