"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import MerchantSelector from "./MerchantSelector";
import { operationalStatusLabel } from "./status-presentation";

type Scope = "backoffice" | "merchant";
type Property = { id:string; name:string; slug:string; city:string; sourceType:string; publicationStatus:string; operationalStatus:string; upcomingBookings:number; roomTypes:unknown[] };
type Pagination = { page:number; perPage:number; total:number; totalPages?:number };
const emptyForm={organizationId:"",name:"",slug:"",city:"",country:"ایران",address:"",area:"",stars:4,description:"",checkInTime:"14:00",checkOutTime:"12:00"};

export default function HotelPropertyList({scope}:{scope:Scope}){
  const[items,setItems]=useState<Property[]>([]);const[pagination,setPagination]=useState<Pagination>({page:1,perPage:20,total:0});
  const[filters,setFilters]=useState({search:"",city:"",publicationStatus:""});const[form,setForm]=useState(emptyForm);
  const[error,setError]=useState("");const[loading,setLoading]=useState(false);const[creating,setCreating]=useState(false);
  const endpoint=useMemo(()=>{const query=new URLSearchParams({page:String(pagination.page),perPage:String(pagination.perPage)});Object.entries(filters).forEach(([key,value])=>value&&query.set(key,value));return `/api/${scope}/hotels?${query}`},[scope,filters,pagination.page,pagination.perPage]);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(endpoint,{credentials:"include",cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error?.message??"دریافت هتل‌ها ممکن نشد");setItems(body.properties??[]);setPagination(current=>({...current,...body.pagination}))}catch(reason){setError(reason instanceof Error?reason.message:"خطای ناشناخته")}finally{setLoading(false)}},[endpoint]);
  useEffect(()=>{void load()},[load]);
  const changeFilter=(key:string,value:string)=>{setPagination(current=>({...current,page:1}));setFilters(current=>({...current,[key]:value}))};
  const create=async()=>{if(scope==="backoffice"&&!form.organizationId)return setError("پذیرنده هتل را انتخاب کنید");setCreating(true);setError("");try{const payload=scope==="backoffice"?form:Object.fromEntries(Object.entries(form).filter(([key])=>key!=="organizationId"));const response=await fetch(`/api/${scope}/hotels`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,stars:Number(form.stars),area:form.area||null})});const body=await response.json();if(!response.ok)throw new Error(body.error?.message??"ساخت هتل ناموفق بود");setForm(emptyForm);await load()}catch(reason){setError(reason instanceof Error?reason.message:"خطای ناشناخته")}finally{setCreating(false)}};
  const pages=pagination.totalPages??Math.max(1,Math.ceil(pagination.total/pagination.perPage));
  const field=(label:string,key:keyof typeof emptyForm,props:Record<string,unknown>={})=><label className="text-xs font-bold">{label}<input {...props} value={form[key]} onChange={event=>setForm(current=>({...current,[key]:event.target.value}))} className="mt-1 min-h-11 w-full rounded-xl border px-3 font-normal"/></label>;
  return <div className="space-y-5">
    <section className="rounded-3xl border bg-white p-5 shadow-sm"><h1 className="text-xl font-black">ساخت هتل مستقیم</h1><p className="mt-1 text-sm text-slate-500">هتل ابتدا پیش‌نویس است؛ اطلاعات، اتاق، نرخ و موجودی را پیش از ارسال برای بررسی کامل کنید.</p><div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{scope==="backoffice"&&<MerchantSelector businessType="HOTEL" value={form.organizationId} onChange={organizationId=>setForm(current=>({...current,organizationId}))} label="پذیرنده هتل"/>}{field("نام هتل","name",{required:true})}{field("شناسه پایدار انگلیسی","slug",{dir:"ltr",placeholder:"hotel-stable-slug"})}{field("شهر","city")}{field("کشور","country")}{field("نشانی","address")}{field("منطقه","area")}<label className="text-xs font-bold">تعداد ستاره<select value={form.stars} onChange={event=>setForm(current=>({...current,stars:Number(event.target.value)}))} className="mt-1 min-h-11 w-full rounded-xl border bg-white px-3 font-normal">{[1,2,3,4,5].map(star=><option key={star} value={star}>{star.toLocaleString("fa-IR")} ستاره</option>)}</select></label>{field("ساعت ورود","checkInTime",{type:"time"})}{field("ساعت خروج","checkOutTime",{type:"time"})}<label className="text-xs font-bold sm:col-span-2 lg:col-span-3">توضیحات<textarea value={form.description} onChange={event=>setForm(current=>({...current,description:event.target.value}))} className="mt-1 min-h-24 w-full rounded-xl border p-3 font-normal"/></label></div><button type="button" disabled={creating} onClick={()=>void create()} className="mt-4 min-h-11 rounded-xl bg-primary px-5 text-sm font-bold text-white disabled:opacity-50">{creating?"در حال ساخت…":"ساخت پیش‌نویس هتل"}</button></section>
    {error&&<p role="alert" className="rounded-2xl bg-red-50 p-4 text-sm text-red-800">{error}</p>}
    <section className="rounded-3xl border bg-white p-5 shadow-sm"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><h2 className="text-xl font-black">هتل‌ها</h2><p className="mt-1 text-xs text-slate-500">جست‌وجو و فیلتر روی سرور انجام می‌شود.</p></div><div className="grid gap-2 sm:grid-cols-3"><label className="text-xs font-bold">جست‌وجو<input value={filters.search} onChange={event=>changeFilter("search",event.target.value)} className="mt-1 min-h-10 rounded-xl border px-3 font-normal" placeholder="نام یا شناسه"/></label><label className="text-xs font-bold">شهر<input value={filters.city} onChange={event=>changeFilter("city",event.target.value)} className="mt-1 min-h-10 rounded-xl border px-3 font-normal"/></label><label className="text-xs font-bold">وضعیت انتشار<select value={filters.publicationStatus} onChange={event=>changeFilter("publicationStatus",event.target.value)} className="mt-1 min-h-10 rounded-xl border bg-white px-3 font-normal"><option value="">همه</option>{["DRAFT","SUBMITTED","NEEDS_CHANGES","PUBLISHED","PAUSED","ARCHIVED"].map(value=><option key={value} value={value}>{operationalStatusLabel(value)}</option>)}</select></label></div></div>
      <div className="mt-5 space-y-3">{loading&&<p className="py-10 text-center text-sm text-slate-500">در حال دریافت…</p>}{!loading&&items.map(item=><article key={item.id} className="flex flex-col justify-between gap-4 rounded-2xl border p-4 lg:flex-row lg:items-center"><div><div className="flex flex-wrap gap-2 text-[11px] font-bold"><span className="rounded-full bg-red-50 px-2 py-1 text-primary">{item.sourceType}</span><span className="rounded-full bg-slate-100 px-2 py-1">{operationalStatusLabel(item.publicationStatus)}</span><span className="rounded-full bg-slate-100 px-2 py-1">{operationalStatusLabel(item.operationalStatus)}</span></div><h3 className="mt-2 font-black">{item.name}</h3><p className="mt-1 text-xs text-slate-500">{item.city} · {item.roomTypes.length.toLocaleString("fa-IR")} نوع اتاق · {item.upcomingBookings.toLocaleString("fa-IR")} رزرو پیش‌رو</p></div><Link href={`/${scope}/hotels/${item.id}`} className="rounded-xl border px-4 py-2 text-center text-xs font-bold">مدیریت هتل</Link></article>)}{!loading&&!items.length&&<p className="py-12 text-center text-sm text-slate-500">هتلی با این فیلتر پیدا نشد.</p>}</div>
      <nav aria-label="صفحه‌بندی هتل‌ها" className="mt-5 flex items-center justify-between gap-3 border-t pt-4"><button disabled={pagination.page<=1} onClick={()=>setPagination(current=>({...current,page:current.page-1}))} className="rounded-lg border px-4 py-2 text-xs font-bold disabled:opacity-40">صفحه قبل</button><span className="text-center text-xs text-slate-500">صفحه {pagination.page.toLocaleString("fa-IR")} از {pages.toLocaleString("fa-IR")} · {pagination.total.toLocaleString("fa-IR")} هتل</span><button disabled={pagination.page>=pages} onClick={()=>setPagination(current=>({...current,page:current.page+1}))} className="rounded-lg border px-4 py-2 text-xs font-bold disabled:opacity-40">صفحه بعد</button></nav>
    </section>
  </div>;
}
