"use client";

import { useCallback, useEffect, useState } from "react";
import { operationalStatusLabel } from "./status-presentation";

type Member={id:string;status:string;user:{firstName:string;lastName:string;mobile:string;email:string};roles:Array<{code:string;name:string}>;joinedAt:string|null};
const roleLabels:Record<string,string>={MERCHANT_OWNER:"مالک سازمان",MERCHANT_MANAGER:"مدیر پذیرنده",MERCHANT_FINANCE:"کارشناس مالی",MERCHANT_OPERATOR:"کارشناس عملیات",MERCHANT_READONLY:"مشاهده‌گر"};
const roles=Object.keys(roleLabels);

export default function MerchantTeam(){
  const[rows,setRows]=useState<Member[]>([]);const[error,setError]=useState("");const[saving,setSaving]=useState<string|null>(null);
  const load=useCallback(async()=>{const response=await fetch("/api/merchant/team",{credentials:"include",cache:"no-store"});const body=await response.json();if(!response.ok){setError(body.error?.message??"دریافت تیم ممکن نشد");return}setRows(body.team??[])},[]);
  useEffect(()=>{void load()},[load]);
  const mutate=async(member:Member,path:string,payload:Record<string,string>)=>{const currentOwner=member.roles.some(role=>role.code==="MERCHANT_OWNER");const ownerChange=currentOwner||payload.roles==="MERCHANT_OWNER";const suspending=payload.status==="SUSPENDED";if((ownerChange||suspending)&&!window.confirm(ownerChange?"تغییر نقش مالک دسترسی‌های حساس سازمان را عوض می‌کند. ادامه می‌دهید؟":"این عضو غیرفعال شود؟"))return;setSaving(member.id);setError("");const response=await fetch(`/api/merchant/team/${member.id}${path}`,{method:path?"PUT":"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(path?{roles:[payload.roles]}:payload)});const body=await response.json();setSaving(null);if(!response.ok){setError(body.error?.message??"تغییر عضو ممکن نشد");return}await load()};
  return <section className="rounded-3xl border bg-white p-5 shadow-sm"><h1 className="text-2xl font-black">تیم پذیرنده</h1><p className="mt-1 text-sm text-slate-500">فقط نقش‌های ازپیش‌تعریف‌شده قابل انتخاب‌اند. آخرین مالک فعال در سرور محافظت می‌شود.</p>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="mt-5 space-y-3">{rows.map(member=><article key={member.id} className="flex flex-col justify-between gap-4 rounded-2xl border p-4 lg:flex-row lg:items-center"><div><b>{member.user.firstName} {member.user.lastName}</b><p className="mt-1 text-xs text-slate-500">{member.user.mobile} · {member.user.email||"بدون ایمیل"} · {operationalStatusLabel(member.status)}</p><p className="mt-1 text-xs font-bold text-primary">{member.roles.map(role=>roleLabels[role.code]??role.name).join("، ")||"بدون نقش"}</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="text-xs font-bold">نقش<select aria-label={`نقش ${member.user.firstName}`} disabled={saving===member.id} value={member.roles[0]?.code??"MERCHANT_READONLY"} onChange={event=>void mutate(member,"/roles",{roles:event.target.value})} className="mt-1 min-h-10 rounded-xl border bg-white px-3 text-xs font-bold disabled:opacity-50">{roles.map(role=><option key={role} value={role}>{roleLabels[role]}</option>)}</select></label><button disabled={saving===member.id} onClick={()=>void mutate(member,"",{status:member.status==="ACTIVE"?"SUSPENDED":"ACTIVE"})} className="self-end rounded-xl border px-3 py-2 text-xs font-bold disabled:opacity-50">{saving===member.id?"در حال ثبت…":member.status==="ACTIVE"?"غیرفعال‌کردن عضو":"فعال‌کردن عضو"}</button></div></article>)}</div><p className="mt-5 rounded-xl bg-amber-50 p-3 text-xs leading-6 text-amber-900">دعوت امن هنوز فعال نشده است؛ کاربر ضمنی ساخته نمی‌شود.</p></section>;
}
