"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { CalendarPlus, Copy, Plus, Send, ShieldCheck } from "lucide-react";

type Scope = "backoffice" | "merchant";
type Program = { id: string; title: string; slug: string; type: string; publicationStatus: string; organization?: { name: string }; destinations: Array<{ label: string }>; departures: Array<{ id: string; startDate: string; effectiveSaleStatus: string; capacity: { remaining: number } }>; registrationCount: number; remainingCapacity: number; startingPrice: number | null; updatedAt: string };

export default function ProgramManagement({ scope }: { scope: Scope }) {
  const [programs, setPrograms] = useState<Program[]>([]); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const [draft, setDraft] = useState({ type: "TOUR", title: "", slug: "" });
  const base = `/api/${scope}/programs`;
  const load = useCallback(() => fetch(base, { credentials: "include", cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error?.message); setPrograms(body.programs ?? []); }).catch((reason) => setError(reason.message ?? "خطا در دریافت برنامه‌ها")), [base]);
  useEffect(() => { void load(); }, [load]);
  const mutate = async (url: string, body: unknown) => { setBusy(url); setError(""); try { const response = await fetch(url, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json(); if (!response.ok) throw new Error(result.error?.message); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "عملیات ناموفق بود"); } finally { setBusy(""); } };
  const create = async () => { if (!draft.title || !draft.slug) return setError("عنوان و slug الزامی است."); await mutate(base, scope === "backoffice" ? { ...draft, organizationId: prompt("شناسه UUID پذیرنده") } : draft); setDraft({ type: "TOUR", title: "", slug: "" }); };
  return <div className="space-y-5">
    <section className="rounded-3xl border bg-white p-5 shadow-sm sm:p-7"><div className="flex items-center gap-2"><Plus className="size-5 text-primary"/><h2 className="text-xl font-black">برنامهٔ جدید</h2></div><p className="mt-2 text-sm text-slate-500">ابتدا پیش‌نویس بسازید؛ سپس مقصد، حرکت، قیمت، itinerary، خدمات، قوانین و تصاویر را تکمیل کنید.</p><div className="mt-5 grid gap-3 sm:grid-cols-[150px_1fr_1fr_auto]"><select className="min-h-11 rounded-xl border px-3" value={draft.type} onChange={(e)=>setDraft({...draft,type:e.target.value})}><option value="TOUR">تور</option><option value="ZIYARAT">زیارت</option></select><input className="min-h-11 rounded-xl border px-3" placeholder="عنوان برنامه" value={draft.title} onChange={(e)=>setDraft({...draft,title:e.target.value})}/><input dir="ltr" className="min-h-11 rounded-xl border px-3" placeholder="slug-english" value={draft.slug} onChange={(e)=>setDraft({...draft,slug:e.target.value})}/><button onClick={create} disabled={!!busy} className="rounded-xl bg-primary px-5 text-sm font-bold text-white">ساخت پیش‌نویس</button></div></section>
    {error && <p role="alert" className="rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">{error}</p>}
    <section className="rounded-3xl border bg-white p-4 shadow-sm sm:p-6"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-black">برنامه‌ها</h2><span className="text-xs text-slate-500">{programs.length.toLocaleString("fa-IR")} رکورد</span></div><div className="space-y-3">{programs.map((program)=><article key={program.id} className="rounded-2xl border p-4"><div className="flex flex-col justify-between gap-4 lg:flex-row"><div><div className="flex flex-wrap gap-2 text-[11px] font-bold"><span className="rounded-full bg-red-50 px-2.5 py-1 text-primary">{program.type === "TOUR" ? "تور" : "زیارت"}</span><span className="rounded-full bg-slate-100 px-2.5 py-1">{program.publicationStatus}</span>{program.organization&&<span>{program.organization.name}</span>}</div><h3 className="mt-2 font-black">{program.title}</h3><p className="mt-1 text-xs text-slate-500">{program.destinations.map((item)=>item.label).join("، ") || "مقصد تکمیل نشده"}</p></div><div className="grid grid-cols-3 gap-2 text-center text-xs"><div className="rounded-xl bg-slate-50 p-3"><b className="block text-base">{program.departures.length.toLocaleString("fa-IR")}</b>حرکت</div><div className="rounded-xl bg-slate-50 p-3"><b className="block text-base">{program.registrationCount.toLocaleString("fa-IR")}</b>ثبت‌نام</div><div className="rounded-xl bg-red-50 p-3"><b className="block text-base text-primary">{program.remainingCapacity.toLocaleString("fa-IR")}</b>ظرفیت</div></div></div><div className="mt-4 flex flex-wrap gap-2 border-t pt-3"><Link href={`/${scope}/programs/${program.id}`} className="rounded-lg border px-3 py-2 text-xs font-bold">ویرایش و حرکت‌ها</Link><button onClick={()=>mutate(`${base}/${program.id}/duplicate`,{})} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-xs font-bold"><Copy className="size-3.5"/>کپی</button>{scope==="merchant"&&["DRAFT","NEEDS_CHANGES","REJECTED"].includes(program.publicationStatus)&&<button onClick={()=>mutate(`${base}/${program.id}/workflow`,{status:"SUBMITTED"})} className="inline-flex items-center gap-1 rounded-lg bg-primary px-3 py-2 text-xs font-bold text-white"><Send className="size-3.5"/>ارسال بررسی</button>}{scope==="backoffice"&&program.publicationStatus==="SUBMITTED"&&<button onClick={()=>mutate(`${base}/${program.id}/moderation`,{status:"PUBLISHED"})} className="inline-flex items-center gap-1 rounded-lg bg-emerald-600 px-3 py-2 text-xs font-bold text-white"><ShieldCheck className="size-3.5"/>انتشار</button>}<span className="inline-flex items-center gap-1 text-xs text-slate-500"><CalendarPlus className="size-3.5"/>آخرین تغییر {new Date(program.updatedAt).toLocaleDateString("fa-IR")}</span></div></article>)}{!programs.length&&<p className="py-12 text-center text-sm text-slate-500">برنامه‌ای ثبت نشده است.</p>}</div></section>
  </div>;
}
