"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { operationalStatusLabel } from "./status-presentation";

type Scope="backoffice"|"merchant";
type Ticket={id:string;subject:string;category:string;status:string;internalNote?:string|null;organization?:{name:string}|null;order?:{orderNumber:string;trackingCode:string;serviceType:string}|null;messages:Array<{id:string;authorType:string;body:string;internal?:boolean;createdAt:string}>};

export default function SupportDetail({scope,id}:{scope:Scope;id:string}){
  const endpoint=`/api/${scope}/support/${id}`;const[ticket,setTicket]=useState<Ticket|null>(null);const[body,setBody]=useState("");const[internal,setInternal]=useState(false);const[error,setError]=useState("");const[busy,setBusy]=useState(false);
  const load=useCallback(()=>fetch(endpoint,{credentials:"include",cache:"no-store"}).then(async r=>{const value=await r.json();if(!r.ok)throw new Error(value.error?.message??"درخواست دریافت نشد");setTicket(value.ticket)}).catch(reason=>setError(reason.message)),[endpoint]);useEffect(()=>{void load()},[load]);
  const reply=async()=>{if(!body.trim())return;setBusy(true);setError("");const response=await fetch(`${endpoint}/replies`,{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(scope==="backoffice"?{body,internal}:{body})});const value=await response.json().catch(()=>({}));setBusy(false);if(!response.ok)return setError(value.error?.message??"ارسال پاسخ ناموفق بود");setBody("");setInternal(false);void load()};
  if(!ticket)return <div className="rounded-3xl border bg-white p-8 text-center">{error||"در حال دریافت درخواست…"}</div>;
  return <div className="space-y-5"><div><Link href={`/${scope}/support`} className="text-xs font-bold text-primary">بازگشت به پشتیبانی</Link><h1 className="mt-2 text-2xl font-black">{ticket.subject}</h1><p className="mt-1 text-sm text-slate-500">{ticket.category} · {operationalStatusLabel(ticket.status)}{ticket.organization?` · ${ticket.organization.name}`:""}</p></div>{ticket.order&&<section className="rounded-2xl border bg-white p-4 text-sm"><b>سفارش مرتبط: {ticket.order.orderNumber}</b><p className="mt-1 text-xs text-slate-500">{ticket.order.trackingCode} · {ticket.order.serviceType}</p></section>}{error&&<p className="rounded-2xl bg-red-50 p-4 text-sm text-red-800">{error}</p>}<section className="rounded-3xl border bg-white p-5"><h2 className="font-black">گفت‌وگو</h2><div className="mt-4 space-y-3">{ticket.messages.map(message=><article key={message.id} className={`max-w-3xl rounded-2xl p-4 text-sm ${message.internal?"border border-amber-200 bg-amber-50":message.authorType==="merchant"?"mr-auto bg-red-50":"ml-auto bg-slate-100"}`}><div className="flex items-center justify-between gap-3"><b>{message.internal?"یادداشت داخلی":message.authorType==="merchant"?"پذیرنده":"پشتیبانی کیاشی"}</b><time className="text-[11px] text-slate-500">{new Date(message.createdAt).toLocaleString("fa-IR")}</time></div><p className="mt-2 leading-7">{message.body}</p></article>)}</div></section><section className="rounded-3xl border bg-white p-5"><h2 className="font-black">پاسخ جدید</h2><textarea value={body} onChange={e=>setBody(e.target.value)} className="mt-3 min-h-32 w-full rounded-xl border p-3" placeholder="متن پاسخ روشن و قابل پیگیری…"/>{scope==="backoffice"&&<label className="mt-3 flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={internal} onChange={e=>setInternal(e.target.checked)}/>یادداشت داخلی؛ پذیرنده آن را نمی‌بیند</label>}<button disabled={busy||!body.trim()||ticket.status==="closed"} onClick={reply} className="mt-4 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-white disabled:opacity-40">ارسال پاسخ</button></section></div>;
}
