"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, FileCheck2, ShieldAlert } from "lucide-react";
import { operationalStatusLabel } from "./status-presentation";

type VisaListRow={id:string;country:string;status:string;applicant:{name:string;mobile:string};submittedAt:string|null;missingDocuments:number;reviewerId:string|null;updatedAt:string};
type ChecklistEntry={status:string;note?:string};
type VisaDetail={id:string;country:string;status:string;applicant:{name:string;mobile:string;email:string;nationalId:string};travelDates:unknown;purpose:unknown;checklist:Record<string,ChecklistEntry>;internalNote:string|null;customerNote:string|null;providerReference:string|null;reviewer:{id:string;name:string}|null;timeline:Array<{status:string;at:string;audience:string;note?:string}>;audit:Array<{id:string;action:string;createdAt:string}>;submittedAt:string|null;updatedAt:string};

const statuses=["DRAFT","SUBMITTED","DOCUMENTS_REQUIRED","UNDER_REVIEW","READY_FOR_SUBMISSION","SUBMITTED_TO_PROVIDER","DECISION_RECEIVED","COMPLETED","REJECTED","CANCELLED"];
const documentLabels:Record<string,string>={passport:"گذرنامه",photo:"عکس",insurance:"بیمه",financialProof:"تمکن مالی",reservations:"رزروها",applicationForms:"فرم درخواست"};
const documentStates=["missing","requested","received","verified","not_required"];
const documentStateLabels:Record<string,string>={missing:"ناقص",requested:"درخواست‌شده",received:"دریافت‌شده",verified:"تأییدشده",not_required:"لازم نیست"};
const nextStatuses:Record<string,string[]>={DRAFT:["SUBMITTED","CANCELLED"],SUBMITTED:["DOCUMENTS_REQUIRED","UNDER_REVIEW","CANCELLED"],DOCUMENTS_REQUIRED:["SUBMITTED","CANCELLED"],UNDER_REVIEW:["DOCUMENTS_REQUIRED","READY_FOR_SUBMISSION","REJECTED","CANCELLED"],READY_FOR_SUBMISSION:["SUBMITTED_TO_PROVIDER","DOCUMENTS_REQUIRED","CANCELLED"],SUBMITTED_TO_PROVIDER:["DECISION_RECEIVED"],DECISION_RECEIVED:["COMPLETED","REJECTED"],COMPLETED:[],REJECTED:[],CANCELLED:[]};
const faDate=(value:string|null)=>value?new Date(value).toLocaleString("fa-IR"):"—";

export function VisaCaseList(){
  const[rows,setRows]=useState<VisaListRow[]>([]);const[filters,setFilters]=useState({query:"",country:"",status:""});const[error,setError]=useState("");
  const load=useCallback(async()=>{setError("");const query=new URLSearchParams(Object.fromEntries(Object.entries(filters).filter(([,value])=>value)));const response=await fetch(`/api/backoffice/visa?${query}`,{credentials:"include",cache:"no-store"});const body=await response.json();if(!response.ok){setError(body.error?.message??"دریافت پرونده‌ها ممکن نشد");return}setRows(body.applications??[])},[filters]);
  useEffect(()=>{void load()},[load]);
  return <section className="rounded-3xl border bg-white p-5 shadow-sm sm:p-6"><div className="flex items-start gap-3"><FileCheck2 className="mt-1 size-7 text-primary"/><div><h1 className="text-2xl font-black">پرونده‌های ویزا</h1><p className="mt-1 text-sm leading-7 text-slate-500">مدیریت پرونده، مدارک و وضعیت واقعی؛ بدون ادعای تأیید سفارت یا صدور ویزا.</p></div></div><div className="mt-5 grid gap-2 sm:grid-cols-2 lg:grid-cols-4"><input aria-label="جست‌وجوی پرونده" className="min-h-11 rounded-xl border px-3 text-sm" value={filters.query} onChange={event=>setFilters({...filters,query:event.target.value})} placeholder="شناسه، نام یا موبایل"/><input aria-label="کشور" className="min-h-11 rounded-xl border px-3 text-sm" value={filters.country} onChange={event=>setFilters({...filters,country:event.target.value})} placeholder="کشور"/><select aria-label="وضعیت" className="min-h-11 rounded-xl border bg-white px-3 text-sm" value={filters.status} onChange={event=>setFilters({...filters,status:event.target.value})}><option value="">همه وضعیت‌ها</option>{statuses.map(status=><option key={status} value={status}>{operationalStatusLabel(status)}</option>)}</select><button onClick={()=>void load()} className="rounded-xl bg-primary px-4 text-sm font-bold text-white">اعمال فیلتر</button></div>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}<div className="mt-5 overflow-x-auto"><table className="w-full min-w-[900px] text-right text-sm"><thead className="bg-slate-50 text-xs"><tr>{["پرونده","متقاضی","کشور","وضعیت","مدارک ناقص","کارشناس","آخرین تغییر"].map(title=><th key={title} className="p-4">{title}</th>)}</tr></thead><tbody>{rows.map(row=><tr key={row.id} className="border-t"><td className="p-4"><Link className="font-black text-primary" href={`/backoffice/visa/${row.id}`}>{row.id.slice(0,8)}</Link></td><td className="p-4"><b>{row.applicant.name}</b><small className="block text-slate-500">{row.applicant.mobile}</small></td><td className="p-4">{row.country}</td><td className="p-4 font-bold">{operationalStatusLabel(row.status)}</td><td className="p-4">{row.missingDocuments.toLocaleString("fa-IR")}</td><td className="p-4">{row.reviewerId?"تخصیص‌یافته":"تخصیص‌نیافته"}</td><td className="p-4">{faDate(row.updatedAt)}</td></tr>)}{rows.length===0&&<tr><td colSpan={7} className="p-12 text-center text-slate-500">پرونده‌ای با این فیلتر پیدا نشد.</td></tr>}</tbody></table></div></section>
}

export function VisaCaseDetail({id}:{id:string}){
  const[data,setData]=useState<VisaDetail|null>(null);const[error,setError]=useState("");const[saving,setSaving]=useState(false);const[form,setForm]=useState({status:"",internalNote:"",customerNote:"",providerReference:"",reviewerId:""});
  const load=useCallback(async()=>{const response=await fetch(`/api/backoffice/visa/${id}`,{credentials:"include",cache:"no-store"});const body=await response.json();if(!response.ok){setError(body.error?.message??"پرونده دریافت نشد");return}setData(body.application);setForm({status:body.application.status,internalNote:body.application.internalNote??"",customerNote:body.application.customerNote??"",providerReference:body.application.providerReference??"",reviewerId:body.application.reviewer?.id??""})},[id]);
  useEffect(()=>{void load()},[load]);
  const update=async(payload:Record<string,unknown>)=>{setSaving(true);setError("");const response=await fetch(`/api/backoffice/visa/${id}`,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const body=await response.json();setSaving(false);if(!response.ok){setError(body.error?.message??"ثبت تغییر ممکن نشد");return}setData(body.application)};
  if(!data)return <div className="rounded-3xl border bg-white p-10 text-center">{error||"در حال دریافت پرونده…"}</div>;
  return <div className="space-y-5"><Link href="/backoffice/visa" className="text-sm font-bold text-primary">بازگشت به پرونده‌ها</Link><section className="rounded-3xl border bg-white p-5 shadow-sm sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><p className="text-xs font-bold text-primary">پرونده {data.id.slice(0,8)}</p><h1 className="mt-2 text-2xl font-black">ویزای {data.country}</h1><p className="mt-2 text-sm text-slate-500">{data.applicant.name} · {data.applicant.mobile} · {data.applicant.email}</p></div><div className="h-fit rounded-2xl bg-red-50 px-4 py-3 font-black text-primary">{operationalStatusLabel(data.status)}</div></div><div className="mt-5 grid gap-3 sm:grid-cols-3">{[["هدف سفر",data.purpose],["تاریخ سفر",data.travelDates],["کارشناس",data.reviewer?.name]].map(([label,value])=><div key={String(label)} className="rounded-2xl bg-slate-50 p-4"><small>{String(label)}</small><b className="mt-1 block">{value?typeof value==="object"?JSON.stringify(value):String(value):"—"}</b></div>)}</div></section>
  <section className="rounded-3xl border bg-white p-5"><h2 className="text-lg font-black">چک‌لیست مدارک</h2><p className="mt-1 text-xs text-slate-500">فقط فراداده ثبت می‌شود؛ فایل مدرک در این مرحله آپلود نمی‌شود.</p><div className="mt-4 grid gap-3 md:grid-cols-2 lg:grid-cols-3">{Object.entries(data.checklist).map(([key,entry])=><label key={key} className="rounded-2xl border p-4"><span className="flex items-center gap-2 font-bold"><CheckCircle2 className="size-4 text-primary"/>{documentLabels[key]??key}</span><select value={entry.status} onChange={event=>void update({checklist:{[key]:{...entry,status:event.target.value}}})} className="mt-3 min-h-10 w-full rounded-xl border bg-white px-3 text-sm">{documentStates.map(status=><option key={status} value={status}>{documentStateLabels[status]}</option>)}</select>{entry.note&&<small className="mt-2 block text-slate-500">{entry.note}</small>}</label>)}</div></section>
  <section className="rounded-3xl border bg-white p-5"><h2 className="text-lg font-black">اقدام پرونده</h2><p className="mt-1 text-xs text-slate-500">فقط انتقال‌های مجاز وضعیت فعلی نمایش داده می‌شوند.</p><div className="mt-4 grid gap-3 md:grid-cols-2"><label className="text-xs font-bold">اقدام بعدی<select value={form.status} onChange={event=>setForm({...form,status:event.target.value})} className="mt-2 min-h-11 w-full rounded-xl border bg-white px-3"><option value={data.status}>بدون تغییر وضعیت · {operationalStatusLabel(data.status)}</option>{(nextStatuses[data.status]??[]).map(status=><option key={status} value={status}>{operationalStatusLabel(status)}</option>)}</select></label><label className="text-xs font-bold">مرجع تأمین‌کننده<input value={form.providerReference} onChange={event=>setForm({...form,providerReference:event.target.value})} className="mt-2 min-h-11 w-full rounded-xl border px-3" placeholder="برای ارسال به تأمین‌کننده الزامی است"/></label><label className="text-xs font-bold">یادداشت قابل نمایش به مشتری<textarea value={form.customerNote} onChange={event=>setForm({...form,customerNote:event.target.value})} className="mt-2 min-h-28 w-full rounded-xl border p-3"/></label><label className="text-xs font-bold">یادداشت داخلی (برای مشتری نمایش داده نمی‌شود)<textarea value={form.internalNote} onChange={event=>setForm({...form,internalNote:event.target.value})} className="mt-2 min-h-28 w-full rounded-xl border p-3"/></label></div>{error&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}<button disabled={saving} onClick={()=>void update({status:form.status,providerReference:form.providerReference||null,customerNote:form.customerNote||null,internalNote:form.internalNote||null})} className="mt-4 rounded-xl bg-primary px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{saving?"در حال ثبت…":"ثبت تغییرات کنترل‌شده"}</button></section>
  <section className="grid gap-5 lg:grid-cols-2"><div className="rounded-3xl border bg-white p-5"><h2 className="font-black">روند قابل نمایش به مشتری</h2><div className="mt-4 space-y-3">{data.timeline.filter(entry=>entry.audience!=="internal").map((entry,index)=><div key={`${entry.at}-${index}`} className="border-r-2 border-red-200 pr-3"><b className="text-sm">{operationalStatusLabel(entry.status)}</b><p className="text-xs text-slate-500">{entry.note} · {faDate(entry.at)}</p></div>)}</div></div><div className="rounded-3xl border bg-white p-5"><h2 className="flex items-center gap-2 font-black"><ShieldAlert className="size-4 text-primary"/>ممیزی داخلی</h2><div className="mt-4 space-y-3">{data.audit.map(entry=><div key={entry.id} className="rounded-xl bg-slate-50 p-3"><b className="text-sm">{entry.action}</b><small className="block text-slate-500">{faDate(entry.createdAt)}</small></div>)}</div></div></section></div>
}
