import type { HotelFilters } from '@/types/hotel';
import { hotelAmenities } from '@/data/hotels';

const Toggle = ({ checked, label, onChange }: { checked: boolean; label: string; onChange: () => void }) => <label className="flex cursor-pointer items-center gap-2 py-1.5 text-sm"><input type="checkbox" checked={checked} onChange={onChange} className="size-4 accent-primary" /><span>{label}</span></label>;

export const HotelFiltersPanel = ({ filters, areas, onChange, onReset }: { filters: HotelFilters; areas: string[]; onChange: (filters: HotelFilters) => void; onReset: () => void }) => {
  const toggle = (key: 'stars' | 'area' | 'amenities' | 'tags', value: string | number) => { const current = filters[key] as Array<string | number>; onChange({ ...filters, [key]: current.includes(value) ? current.filter((item) => item !== value) : [...current, value] }); };
  return <div className="space-y-5"><div className="flex items-center justify-between"><h2 className="font-extrabold">فیلترها</h2><button type="button" onClick={onReset} className="text-xs font-bold text-primary">پاک‌کردن همه</button></div>
    <fieldset><legend className="mb-2 text-sm font-bold">قیمت هر شب</legend><div className="grid grid-cols-2 gap-2"><label className="text-[11px] text-muted-foreground">حداقل<input type="number" value={filters.minPrice} onChange={(e) => onChange({ ...filters, minPrice: Number(e.target.value) })} className="mt-1 min-h-10 w-full rounded-lg border border-border px-2 text-xs" /></label><label className="text-[11px] text-muted-foreground">حداکثر<input type="number" value={filters.maxPrice} onChange={(e) => onChange({ ...filters, maxPrice: Number(e.target.value) })} className="mt-1 min-h-10 w-full rounded-lg border border-border px-2 text-xs" /></label></div></fieldset>
    <fieldset><legend className="mb-1 text-sm font-bold">ستاره هتل</legend>{[5, 4, 3, 2].map((star) => <Toggle key={star} checked={filters.stars.includes(star)} label={`${star.toLocaleString('fa-IR')} ستاره`} onChange={() => toggle('stars', star)} />)}</fieldset>
    <fieldset><legend className="mb-2 text-sm font-bold">امتیاز کاربران</legend><select value={filters.minRating} onChange={(e) => onChange({ ...filters, minRating: Number(e.target.value) })} className="min-h-10 w-full rounded-lg border border-border bg-background px-2 text-sm"><option value="0">همه امتیازها</option><option value="4.5">۴٫۵ به بالا</option><option value="4">۴ به بالا</option><option value="3.5">۳٫۵ به بالا</option></select></fieldset>
    <fieldset><legend className="mb-1 text-sm font-bold">منطقه</legend>{areas.map((area) => <Toggle key={area} checked={filters.area.includes(area)} label={area} onChange={() => toggle('area', area)} />)}</fieldset>
    <fieldset><legend className="mb-1 text-sm font-bold">امکانات</legend>{hotelAmenities.map((amenity) => <Toggle key={amenity} checked={filters.amenities.includes(amenity)} label={amenity} onChange={() => toggle('amenities', amenity)} />)}</fieldset>
    <fieldset><legend className="mb-2 text-sm font-bold">وعده غذایی</legend><select value={filters.mealPlan} onChange={(e) => onChange({ ...filters, mealPlan: e.target.value as HotelFilters['mealPlan'] })} className="min-h-10 w-full rounded-lg border border-border bg-background px-2 text-sm"><option value="all">همه</option><option value="صبحانه">صبحانه</option><option value="بدون وعده">بدون وعده</option></select></fieldset>
    <fieldset><legend className="mb-2 text-sm font-bold">استرداد</legend><select value={filters.refundable} onChange={(e) => onChange({ ...filters, refundable: e.target.value as HotelFilters['refundable'] })} className="min-h-10 w-full rounded-lg border border-border bg-background px-2 text-sm"><option value="all">همه</option><option value="refundable">قابل استرداد</option><option value="non-refundable">غیرقابل استرداد</option></select></fieldset>
    <fieldset><legend className="mb-1 text-sm font-bold">نوع اقامت</legend>{['مناسب خانواده', 'لوکس', 'اقتصادی', 'نزدیک مرکز'].map((tag) => <Toggle key={tag} checked={filters.tags.includes(tag)} label={tag} onChange={() => toggle('tags', tag)} />)}</fieldset>
  </div>;
};
