import type { AncillaryService, BookingDraft, BookingPassenger, CouponApplication, PriceBreakdown, HotelBookingDraft, ExperienceCheckoutDraft, SecondaryCheckoutDraft } from '@/types/checkout';
import type { FlightResult } from '@/types/flight';
import { calculateNights } from './hotelService';
import { calculateExperiencePrice } from './experienceService';
import { calculateBusPrice, calculateCipPrice, calculateInsurancePrice, calculateTrainPrice, calculateTransferPrice } from './secondaryService';
import type { BusOffer, CipPackage, InsurancePlan, TrainOffer, TransferVehicle } from '@/types/secondary';

export const savedPassengers: BookingPassenger[] = [
  { id: 'saved-reza', savedId: 'saved-reza', type: 'adult', firstNameFa: 'رضا', lastNameFa: 'احمدی', firstNameLatin: 'Reza', lastNameLatin: 'Ahmadi', gender: 'مرد', birthDate: '1990-03-12', nationalId: '0012345678', nationality: 'ایران', passportNumber: 'N12345678', passportCountry: 'ایران', passportExpiry: '2028-05-20' },
  { id: 'saved-sara', savedId: 'saved-sara', type: 'adult', firstNameFa: 'سارا', lastNameFa: 'محمدی', firstNameLatin: 'Sara', lastNameLatin: 'Mohammadi', gender: 'زن', birthDate: '1992-08-21', nationalId: '0023456789', nationality: 'ایران', passportNumber: 'P23456789', passportCountry: 'ایران', passportExpiry: '2029-01-14' },
  { id: 'saved-ali', savedId: 'saved-ali', type: 'adult', firstNameFa: 'علی', lastNameFa: 'احمدی', firstNameLatin: 'Ali', lastNameLatin: 'Ahmadi', gender: 'مرد', birthDate: '1988-11-03', nationalId: '0034567890', nationality: 'ایران', passportNumber: '', passportCountry: 'ایران', passportExpiry: '' },
];
export const ancillaryServices: AncillaryService[] = [{ id: 'insurance-standard', title: 'بیمه مسافرتی استاندارد', description: 'پوشش پایه سفر برای مسیرهای خارجی', price: 850000, applicable: 'international' }, { id: 'insurance-plus', title: 'بیمه مسافرتی پلاس', description: 'پوشش گسترده‌تر سفر، اطلاعات نمونه', price: 1450000, applicable: 'international' }, { id: 'transfer', title: 'ترانسفر فرودگاهی', description: 'خدمت نمونه برای هماهنگی رفت‌وآمد مقصد', price: 650000, applicable: 'all' }];
export const coupons = [{ code: 'TRAVEL500', type: 'fixed', value: 500000, minimum: 5000000 }, { code: 'KIASHI10', type: 'percent', value: 10, maximum: 2000000, minimum: 10000000 }, { code: 'WELCOME', type: 'fixed', value: 300000, minimum: 3000000 }];
export const calculatePrice = (outbound: FlightResult | null, inbound: FlightResult | null, passengers: BookingPassenger[], selectedAncillaries: string[], coupon: CouponApplication | null): PriceBreakdown => { const base = (outbound?.price ?? 0) + (inbound?.price ?? 0); const passengerMultiplier = Math.max(1, passengers.filter((p) => p.type !== 'infant').length); const passengersTotal = base * passengerMultiplier; const ancillariesTotal = selectedAncillaries.reduce((sum, id) => sum + (ancillaryServices.find((item) => item.id === id)?.price ?? 0), 0); const discount = coupon?.discount ?? 0; return { outbound: outbound?.price ?? 0, inbound: inbound?.price ?? 0, passengers: passengersTotal, ancillaries: ancillariesTotal, discount, total: Math.max(0, passengersTotal + ancillariesTotal - discount), currency: 'IRR' }; };
export const calculateHotelPrice = (draft: Pick<HotelBookingDraft, 'hotelRatePlan' | 'hotelSearch' | 'roomCount' | 'hotelAddOns' | 'coupon'>): PriceBreakdown => { const nights = calculateNights(draft.hotelSearch.checkIn, draft.hotelSearch.checkOut); const roomTotal = draft.hotelRatePlan.nightlyPrice * nights * draft.roomCount; const addOns = draft.hotelAddOns.reduce((sum, item) => sum + (item === 'airport-transfer' ? 950000 : item === 'early-checkin' ? 450000 : 0), 0); const discount = draft.coupon?.discount ?? 0; return { outbound: roomTotal, inbound: 0, passengers: roomTotal, ancillaries: addOns, discount, total: Math.max(0, roomTotal + addOns - discount), currency: 'IRR' }; };
export const calculateDraftPrice = (draft: BookingDraft): PriceBreakdown => draft.serviceType === 'hotel' ? calculateHotelPrice(draft as HotelBookingDraft) : calculatePrice(draft.outbound, draft.inbound, draft.passengers, draft.ancillaries, draft.coupon);
export const calculateExperienceDraftPrice = (draft: ExperienceCheckoutDraft): PriceBreakdown => { const pricing = calculateExperiencePrice(draft.offer, draft.departure.id, draft.package.id, draft.travelers, draft.addOns); const discount = draft.coupon?.discount ?? 0; return { outbound: pricing.base, inbound: 0, passengers: pricing.base, ancillaries: pricing.addOns, discount, total: Math.max(0, pricing.total - discount), currency: 'IRR' }; };
export const calculateSecondaryDraftPrice=(draft:SecondaryCheckoutDraft):PriceBreakdown=>{const total=draft.secondaryType==='train'?calculateTrainPrice(draft.item as TrainOffer,draft.quantity):draft.secondaryType==='bus'?calculateBusPrice(draft.item as BusOffer,draft.quantity):draft.secondaryType==='insurance'?calculateInsurancePrice(draft.item as InsurancePlan,draft.quantity):draft.secondaryType==='cip'?calculateCipPrice(draft.item as CipPackage,draft.quantity):calculateTransferPrice(draft.item as TransferVehicle);const discount=draft.coupon?.discount??0;return{outbound:total,inbound:0,passengers:total,ancillaries:0,discount,total:Math.max(0,total-discount),currency:'IRR'};};
export const calculateAnyDraftPrice = (draft: BookingDraft): PriceBreakdown => draft.serviceType === 'tour' || draft.serviceType === 'ziyarat' ? calculateExperienceDraftPrice(draft as ExperienceCheckoutDraft) : ['train','bus','insurance','cip','transfer'].includes(draft.serviceType||'') ? calculateSecondaryDraftPrice(draft as SecondaryCheckoutDraft) : calculateDraftPrice(draft);
export const formatGuestSummary = (adults: number, children: number, rooms: number) => `${rooms} اتاق · ${adults + children} مهمان`;
export const formatRoomSummary = (roomName: string, rateTitle: string) => `${roomName} · ${rateTitle}`;
export const validateCoupon = (code: string, subtotal: number): CouponApplication | null => { const coupon = coupons.find((item) => item.code === code.trim().toUpperCase()); if (!coupon || subtotal < coupon.minimum) return null; const discount = coupon.type === 'percent' ? Math.min(Math.round((subtotal * coupon.value) / 100), coupon.maximum ?? subtotal) : coupon.value; return { code: coupon.code, discount, message: 'کد تخفیف با موفقیت اعمال شد.' }; };
export const blankPassenger = (id: string, type: BookingPassenger['type']): BookingPassenger => ({ id, type, firstNameFa: '', lastNameFa: '', firstNameLatin: '', lastNameLatin: '', gender: '', birthDate: '', nationalId: '', nationality: 'ایران', passportNumber: '', passportCountry: 'ایران', passportExpiry: '' });
