import type { AncillaryService, BookingDraft, BookingPassenger, CouponApplication, PriceBreakdown } from '@/types/checkout';
import type { FlightResult } from '@/types/flight';

export const savedPassengers: BookingPassenger[] = [
  { id: 'saved-reza', savedId: 'saved-reza', type: 'adult', firstNameFa: 'رضا', lastNameFa: 'احمدی', firstNameLatin: 'Reza', lastNameLatin: 'Ahmadi', gender: 'مرد', birthDate: '1990-03-12', nationalId: '0012345678', nationality: 'ایران', passportNumber: 'N12345678', passportCountry: 'ایران', passportExpiry: '2028-05-20' },
  { id: 'saved-sara', savedId: 'saved-sara', type: 'adult', firstNameFa: 'سارا', lastNameFa: 'محمدی', firstNameLatin: 'Sara', lastNameLatin: 'Mohammadi', gender: 'زن', birthDate: '1992-08-21', nationalId: '0023456789', nationality: 'ایران', passportNumber: 'P23456789', passportCountry: 'ایران', passportExpiry: '2029-01-14' },
  { id: 'saved-ali', savedId: 'saved-ali', type: 'adult', firstNameFa: 'علی', lastNameFa: 'احمدی', firstNameLatin: 'Ali', lastNameLatin: 'Ahmadi', gender: 'مرد', birthDate: '1988-11-03', nationalId: '0034567890', nationality: 'ایران', passportNumber: '', passportCountry: 'ایران', passportExpiry: '' },
];
export const ancillaryServices: AncillaryService[] = [{ id: 'insurance-standard', title: 'بیمه مسافرتی استاندارد', description: 'پوشش پایه سفر برای مسیرهای خارجی', price: 850000, applicable: 'international' }, { id: 'insurance-plus', title: 'بیمه مسافرتی پلاس', description: 'پوشش گسترده‌تر سفر، اطلاعات نمونه', price: 1450000, applicable: 'international' }, { id: 'transfer', title: 'ترانسفر فرودگاهی', description: 'خدمت نمونه برای هماهنگی رفت‌وآمد مقصد', price: 650000, applicable: 'all' }];
export const coupons = [{ code: 'TRAVEL500', type: 'fixed', value: 500000, minimum: 5000000 }, { code: 'KIASHI10', type: 'percent', value: 10, maximum: 2000000, minimum: 10000000 }, { code: 'WELCOME', type: 'fixed', value: 300000, minimum: 3000000 }];
export const calculatePrice = (outbound: FlightResult | null, inbound: FlightResult | null, passengers: BookingPassenger[], selectedAncillaries: string[], coupon: CouponApplication | null): PriceBreakdown => { const base = (outbound?.price ?? 0) + (inbound?.price ?? 0); const passengerMultiplier = Math.max(1, passengers.filter((p) => p.type !== 'infant').length); const passengersTotal = base * passengerMultiplier; const ancillariesTotal = selectedAncillaries.reduce((sum, id) => sum + (ancillaryServices.find((item) => item.id === id)?.price ?? 0), 0); const discount = coupon?.discount ?? 0; return { outbound: outbound?.price ?? 0, inbound: inbound?.price ?? 0, passengers: passengersTotal, ancillaries: ancillariesTotal, discount, total: Math.max(0, passengersTotal + ancillariesTotal - discount), currency: 'IRR' }; };
export const validateCoupon = (code: string, subtotal: number): CouponApplication | null => { const coupon = coupons.find((item) => item.code === code.trim().toUpperCase()); if (!coupon || subtotal < coupon.minimum) return null; const discount = coupon.type === 'percent' ? Math.min(Math.round((subtotal * coupon.value) / 100), coupon.maximum ?? subtotal) : coupon.value; return { code: coupon.code, discount, message: 'کد تخفیف با موفقیت اعمال شد.' }; };
export const blankPassenger = (id: string, type: BookingPassenger['type']): BookingPassenger => ({ id, type, firstNameFa: '', lastNameFa: '', firstNameLatin: '', lastNameLatin: '', gender: '', birthDate: '', nationalId: '', nationality: 'ایران', passportNumber: '', passportCountry: 'ایران', passportExpiry: '' });
