import { tours, ziyaratOffers } from '@/data/experiences';
import type { ExperienceFilters, ExperienceOffer, ExperienceType } from '@/types/experience';

export const defaultExperienceFilters: ExperienceFilters = { destination: '', origin: '', maxPrice: 100000000, minDays: 0, maxDays: 30, transport: [], hotelStars: [], visaRequired: 'all', tags: [], accommodation: [] };
export const filterExperiences = (items: ExperienceOffer[], filters: ExperienceFilters) => items.filter((item) => (!filters.destination || item.destinations.some((destination) => destination.includes(filters.destination)) || item.title.includes(filters.destination)) && (!filters.origin || item.origin === filters.origin) && item.startingPrice <= filters.maxPrice && item.durationDays >= filters.minDays && item.durationDays <= filters.maxDays && (!filters.transport.length || item.departureOptions.some((departure) => filters.transport.includes(departure.transport))) && (!filters.hotelStars.length || item.packages.some((pack) => filters.hotelStars.includes(pack.hotelStars))) && (!filters.tags.length || filters.tags.some((tag) => item.tags.includes(tag))) && (!filters.accommodation.length || item.packages.some((pack) => filters.accommodation.includes(pack.name))));
export type ExperienceSort = 'recommended' | 'price' | 'date' | 'duration' | 'luxury';
export const sortExperiences = (items: ExperienceOffer[], mode: ExperienceSort) => [...items].sort((a,b) => { if (mode === 'price') return a.startingPrice - b.startingPrice; if (mode === 'duration') return a.durationDays - b.durationDays; if (mode === 'luxury') return Math.max(...b.packages.map((p) => p.hotelStars)) - Math.max(...a.packages.map((p) => p.hotelStars)); if (mode === 'date') return a.departureOptions[0].startDate.localeCompare(b.departureOptions[0].startDate); return Number(b.featured) - Number(a.featured) || a.startingPrice - b.startingPrice; });
const legacyTourAliases: Record<string, string> = { 'tour-istanbul': 'tour-استانبول-0', 'tour-dubai': 'tour-دبی-0', 'tour-kish': 'tour-کیش-0', 'tour-antalya': 'tour-آنتالیا-0', 'tour-van': 'tour-وان-0', 'tour-ziyarat': 'tour-مشهد-0' };
export const experienceService = { searchTours: (filters = defaultExperienceFilters, sort: ExperienceSort = 'recommended') => sortExperiences(filterExperiences(tours, filters), sort), getTourById: (id: string) => tours.find((item) => item.id === (legacyTourAliases[id] || id) || item.slug === id) ?? null, searchZiyarat: (filters = defaultExperienceFilters, sort: ExperienceSort = 'recommended') => sortExperiences(filterExperiences(ziyaratOffers, filters), sort), getZiyaratById: (id: string) => ziyaratOffers.find((item) => item.id === id || item.slug === id) ?? null };
export const calculateExperiencePrice = (offer: ExperienceOffer, departureId: string, packageId: string, travelers: { ageCategory: 'adult' | 'child' | 'infant' }[], addOns: string[] = []) => { const departure = offer.departureOptions.find((item) => item.id === departureId) ?? offer.departureOptions[0]; const pack = offer.packages.find((item) => item.id === packageId) ?? offer.packages[0]; const adults = travelers.filter((item) => item.ageCategory === 'adult').length; const children = travelers.filter((item) => item.ageCategory === 'child').length; const infants = travelers.filter((item) => item.ageCategory === 'infant').length; const base = adults * pack.pricePerAdult + children * pack.pricePerChild + infants * (pack.pricePerInfant ?? 0); const addOnTotal = addOns.reduce((sum, item) => sum + (item === 'insurance' ? 650000 : 750000), 0); return { departure, pack, base: base || departure.basePrice, addOns: addOnTotal, total: (base || departure.basePrice) + addOnTotal, currency: 'IRR' as const }; };
export const formatTravelerSummary = (travelers: { ageCategory: string }[]) => `${travelers.length.toLocaleString('fa-IR')} مسافر · ${travelers.filter((item) => item.ageCategory === 'adult').length.toLocaleString('fa-IR')} بزرگسال`;
export const getExperienceOffers = (type: ExperienceType) => type === 'tour' ? tours : ziyaratOffers;
