import { useState } from 'react';
import { Check, Info, PlaneTakeoff, Send, Smartphone, Sparkles } from 'lucide-react';
import Layout from '@/components/layout/Layout';
import { Link } from '@/lib/router';

type Kind='fast-track'|'esim'|'city-tours';
const content={
  'fast-track':{title:'Fast Track فرودگاه',eyebrow:'عبور سریع‌تر از فرودگاه',intro:'درخواست نمایشی خدمات همراهی و عبور سریع برای زمان ورود یا خروج. ارائه نهایی پس از اتصال سرویس‌دهنده تأیید می‌شود.',fields:['فرودگاه','شماره پرواز','تاریخ سفر','تعداد مسافر'],plans:[['پایه','راهنمایی و همراهی','۱٬۸۰۰٬۰۰۰'],['پلاس','Fast Track و لانژ نمونه','۳٬۴۰۰٬۰۰۰'],['ویژه','Meet & Assist کامل','۵٬۹۰۰٬۰۰۰']]},
  esim:{title:'eSIM سفر',eyebrow:'اتصال ساده در مقصد',intro:'طرح‌های نمونه اینترنت سفر را مقایسه کنید. فعال‌سازی eSIM در این نسخه انجام نمی‌شود و درخواست شما برای اتصال آینده ثبت می‌شود.',fields:['کشور یا مقصد','حجم اینترنت','مدت اعتبار','مدل دستگاه'],plans:[['آسیا ۳GB','۳ گیگابایت · ۷ روز','۶۹۰٬۰۰۰'],['اروپا ۱۰GB','۱۰ گیگابایت · ۳۰ روز','۱٬۹۵۰٬۰۰۰'],['جهانی ۲۰GB','۲۰ گیگابایت · ۳۰ روز','۳٬۸۰۰٬۰۰۰']]},
  'city-tours':{title:'تجربه‌ها و تورهای شهری',eyebrow:'مقصد را زندگی کن',intro:'فعالیت‌های شهری سبک را برای الهام و درخواست رزرو ببینید؛ تأمین‌کننده و ظرفیت در این نسخه نمایشی هستند.',fields:['مقصد','تاریخ دلخواه','تعداد نفرات'],plans:[['تور شهری دبی','نیم‌روز · جاذبه‌های اصلی','۲٬۴۰۰٬۰۰۰'],['کروز بسفر استانبول','۳ ساعت · غروب','۱٬۸۰۰٬۰۰۰'],['تفریحات کیش','یک روز · انتخابی','۱٬۶۰۰٬۰۰۰']]},
} as const;
export default function ServiceLanding({kind}:{kind:Kind}){const item=content[kind];const [sent,setSent]=useState(false);return <Layout><main className="bg-muted/40 py-8 sm:py-12"><div className="container-page max-w-5xl"><section className="rounded-2xl bg-[hsl(220_22%_17%)] p-6 text-white sm:p-10"><div className="flex items-start gap-4"><span className="grid size-12 place-items-center rounded-xl bg-white/10 text-[hsl(42_100%_60%)]">{kind==='esim'?<Smartphone className="size-6"/>:kind==='fast-track'?<PlaneTakeoff className="size-6"/>:<Sparkles className="size-6"/>}</span><div><p className="text-xs font-bold text-[hsl(42_100%_60%)]">{item.eyebrow}</p><h1 className="mt-2 text-3xl font-extrabold">{item.title}</h1></div></div><p className="mt-5 max-w-2xl text-sm leading-7 text-white/70">{item.intro}</p></section><section className="mt-6 grid gap-5 lg:grid-cols-[1fr_1.15fr]"><form onSubmit={(e)=>{e.preventDefault();setSent(true)}} className="rounded-2xl border border-border bg-card p-5 sm:p-7"><h2 className="text-xl font-extrabold">درخواست {kind==='esim'?'خرید آزمایشی':'رزرو نمایشی'}</h2><div className="mt-5 space-y-3">{item.fields.map((field)=><label key={field} className="block text-sm font-bold">{field}<input required placeholder={field} className="mt-2 min-h-11 w-full rounded-lg border border-border bg-background px-3 text-sm"/></label>)}</div><button className="mt-5 inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-3 text-sm font-bold text-white"><Send className="size-4"/> ثبت درخواست</button>{sent&&<p className="mt-4 rounded-lg bg-secondary/10 p-3 text-sm font-bold text-secondary">درخواست شما ثبت شد؛ این سرویس هنوز اتصال واقعی ندارد.</p>}</form><div className="space-y-3">{item.plans.map(([name,desc,price])=><article key={name} className="rounded-2xl border border-border bg-card p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-lg font-extrabold">{name}</h2><p className="mt-2 text-sm text-muted-foreground">{desc}</p></div><p className="font-extrabold text-primary">{price} <small className="text-[10px] font-normal">تومان</small></p></div><div className="mt-4 flex items-center gap-2 text-xs text-muted-foreground"><Check className="size-4 text-secondary"/> اطلاعات و قیمت برای نمایش محصول هستند</div></article>)}<div className="flex items-start gap-2 rounded-xl bg-warning/10 p-4 text-xs leading-6 text-warning"><Info className="mt-0.5 size-4 shrink-0"/>هیچ eSIM، Fast Track یا ظرفیت تأمین‌کننده در این نسخه به‌صورت واقعی فعال نمی‌شود.</div></div></section><div className="mt-5 flex flex-wrap gap-2"><Link to="/help" className="rounded-lg border border-border bg-card px-4 py-3 text-sm font-bold">راهنما</Link><Link to="/track-order" className="rounded-lg border border-border bg-card px-4 py-3 text-sm font-bold">پیگیری خرید</Link></div></div></main></Layout>}
