import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import { z } from "zod";
import { DomainError } from "../domain/errors.js";
import { requirePermission, type PermissionCode } from "../platform/permissions.js";
import { requireMerchantPermissionCapability } from "../platform/merchant-capabilities.js";
import { HotelRepository, type PropertyInput, type RateInput, type RoomInput } from "../repositories/hotels.js";
import { PlatformRepository, type PlatformAccessContext } from "../repositories/platform.js";

type Dependencies={repository:HotelRepository;platformRepository:PlatformRepository;env:{WEB_ORIGIN:string;BACKOFFICE_ENABLED:boolean;MERCHANT_PORTAL_ENABLED:boolean};currentUser:(request:FastifyRequest)=>Promise<{id:string}|undefined>;enforceRate:(key:string,limit:number,windowMs:number)=>void;errorResponse:(reply:FastifyReply,status:number,code:string,message:string)=>FastifyReply};
const uuid=z.string().uuid();const pageSchema=z.object({page:z.coerce.number().int().min(1).default(1),perPage:z.coerce.number().int().min(1).max(100).default(20)});const source=z.enum(["DIRECT","SUPPLIER","HYBRID","DEMO"]);const publication=z.enum(["DRAFT","SUBMITTED","NEEDS_CHANGES","REJECTED","PUBLISHED","PAUSED","ARCHIVED"]);const time=z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/);
const propertyFields={name:z.string().trim().min(2).max(180).optional(),city:z.string().trim().min(2).max(100).optional(),country:z.string().trim().min(2).max(100).optional(),address:z.string().trim().min(3).max(1000).optional(),area:z.string().max(120).nullable().optional(),latitude:z.number().min(-90).max(90).nullable().optional(),longitude:z.number().min(-180).max(180).nullable().optional(),stars:z.number().int().min(1).max(5).optional(),description:z.string().max(10000).optional(),checkInTime:time.optional(),checkOutTime:time.optional(),sourceType:source.optional(),supplierCode:z.string().max(120).nullable().optional(),publicationStatus:publication.optional(),operationalStatus:z.enum(["ACTIVE","INACTIVE","SUSPENDED"]).optional(),amenities:z.array(z.string().max(100)).max(100).optional(),policies:z.record(z.unknown()).optional(),images:z.array(z.string().max(1000)).max(30).optional()};
const bookingFilters=z.object({from:z.coerce.date().optional(),to:z.coerce.date().optional(),status:z.string().trim().max(80).optional(),propertyId:uuid.optional()}).refine(value=>!value.from||!value.to||value.from<value.to,{message:"بازه تاریخ معتبر نیست"});
const createProperty=z.object({...propertyFields,slug:z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/),name:z.string().trim().min(2).max(180),city:z.string().trim().min(2).max(100),address:z.string().trim().min(3).max(1000),stars:z.number().int().min(1).max(5)}).refine(v=>!["SUPPLIER","HYBRID"].includes(v.sourceType??"DIRECT")||!!v.supplierCode,{message:"کد تأمین‌کننده الزامی است"});
const updateProperty=z.object(propertyFields).refine(v=>Object.keys(v).length>0);const roomSchema=z.object({name:z.string().trim().min(1).max(180),description:z.string().max(5000),capacity:z.number().int().min(1).max(20),bedType:z.string().trim().min(1).max(180),sizeSqm:z.number().int().min(5).max(1000).nullable().optional(),amenities:z.array(z.string().max(100)).max(100).optional(),images:z.array(z.string().max(1000)).max(30).optional(),status:z.enum(["ACTIVE","INACTIVE"]).optional()});const rateSchema=z.object({title:z.string().trim().min(1).max(180),mealPlan:z.string().max(180),refundable:z.boolean(),cancellationPolicy:z.string().min(3).max(5000),baseRate:z.number().int().min(0).max(2_000_000_000),currency:z.literal("TOMAN").optional(),taxesIncluded:z.boolean().optional(),status:z.enum(["ACTIVE","INACTIVE"]).optional()});
const inventorySchema=z.object({from:z.coerce.date(),to:z.coerce.date(),weekdays:z.array(z.number().int().min(0).max(6)).max(7).optional(),availableRooms:z.number().int().min(0).max(100000).optional(),priceOverride:z.number().int().min(0).max(2_000_000_000).nullable().optional(),closed:z.boolean().optional(),minimumStay:z.number().int().min(1).max(365).optional()}).refine(v=>[v.availableRooms,v.priceOverride,v.closed,v.minimumStay].some(x=>x!==undefined),{message:"حداقل یک تغییر لازم است"});
function pageOf(query:unknown){const p=pageSchema.safeParse(query);if(!p.success)throw new DomainError("VALIDATION_ERROR","صفحه‌بندی معتبر نیست",400);return{page:p.data.page??1,perPage:p.data.perPage??20};}
function actor(request:FastifyRequest,context:PlatformAccessContext){return{userId:context.user.id,organizationId:context.organization.id,requestId:request.id,ipAddress:request.ip,userAgent:request.headers["user-agent"]};}

export async function registerHotelRoutes(app:FastifyInstance,d:Dependencies){async function contextFor(request:FastifyRequest,reply:FastifyReply,scope:"INTERNAL"|"MERCHANT",permission:PermissionCode){if(!(scope==="INTERNAL"?d.env.BACKOFFICE_ENABLED:d.env.MERCHANT_PORTAL_ENABLED))return void d.errorResponse(reply,404,"NOT_FOUND","موردی پیدا نشد");const user=await d.currentUser(request);if(!user)return void d.errorResponse(reply,401,"AUTH_REQUIRED","برای ادامه وارد شوید");const requested=scope==="MERCHANT"&&typeof request.headers["x-organization-id"]==="string"?request.headers["x-organization-id"]:undefined;const context=await d.platformRepository.accessContext(user.id,scope,requested);if(!context)return void d.errorResponse(reply,403,"ACCESS_DENIED","دسترسی ندارید");requirePermission(context.permissions,permission);if(scope==="MERCHANT")requireMerchantPermissionCapability(context.organization.businessType,permission);return context;}function protect(request:FastifyRequest,context:PlatformAccessContext){if(request.headers.origin&&request.headers.origin!==d.env.WEB_ORIGIN)throw new DomainError("CSRF_REJECTED","مبدأ درخواست معتبر نیست",403);d.enforceRate(`hotel:${context.user.id}`,60,600000);}function valid(ids:string[],reply:FastifyReply){if(ids.some(id=>!uuid.safeParse(id).success)){d.errorResponse(reply,400,"VALIDATION_ERROR","شناسه معتبر نیست");return false;}return true;}
  app.get("/api/catalog/hotels",async(request,reply)=>{const parsed=z.object({city:z.string().max(100).optional()}).safeParse(request.query);if(!parsed.success)return d.errorResponse(reply,400,"VALIDATION_ERROR","فیلتر هتل معتبر نیست");return{properties:await d.repository.publicProperties(parsed.data.city)};});
  app.get<{Params:{slug:string}}>("/api/catalog/hotels/:slug",async request=>({property:await d.repository.publicProperty(request.params.slug)}));
  for(const config of [{prefix:"/api/backoffice" as const,scope:"INTERNAL" as const,read:"backoffice.hotels.read" as PermissionCode,manage:"backoffice.hotels.manage" as PermissionCode},{prefix:"/api/merchant" as const,scope:"MERCHANT" as const,read:"merchant.hotels.read" as PermissionCode,manage:"merchant.hotels.manage" as PermissionCode}]){
    app.get(`${config.prefix}/hotels`,async(request,reply)=>{const context=await contextFor(request,reply,config.scope,config.read);if(!context)return;const parsed=z.object({city:z.string().max(100).optional(),sourceType:source.optional(),publicationStatus:publication.optional(),search:z.string().max(180).optional()}).safeParse(request.query);if(!parsed.success)return d.errorResponse(reply,400,"VALIDATION_ERROR","فیلتر هتل معتبر نیست");const page=pageOf(request.query);const result=await d.repository.listProperties(page,parsed.data,config.scope==="MERCHANT"?context.organization.id:undefined);return{properties:result.items,pagination:{...page,total:result.total}};});
    app.get<{Params:{id:string}}>(`${config.prefix}/hotels/:id`,async(request,reply)=>{const context=await contextFor(request,reply,config.scope,config.read);if(!context||!valid([request.params.id],reply))return;return{property:await d.repository.getProperty(request.params.id,config.scope==="MERCHANT"?context.organization.id:undefined)};});
    app.post(`${config.prefix}/hotels`,async(request,reply)=>{const context=await contextFor(request,reply,config.scope,config.manage);if(!context)return;protect(request,context);const schema=config.scope==="INTERNAL"?z.intersection(createProperty,z.object({organizationId:uuid})):createProperty;const parsed=schema.safeParse(request.body);if(!parsed.success)return d.errorResponse(reply,400,"VALIDATION_ERROR","اطلاعات هتل معتبر نیست");const body=parsed.data as typeof parsed.data&{organizationId?:string};if(config.scope==="MERCHANT"&&body.sourceType&&!['DIRECT','DEMO'].includes(body.sourceType))return d.errorResponse(reply,403,"SOURCE_TYPE_FORBIDDEN","پذیرنده فقط هتل مستقیم ثبت می‌کند");const organizationId=config.scope==="INTERNAL"?body.organizationId!:context.organization.id;const{organizationId:_omit,...input}=body;return reply.code(201).send({property:await d.repository.createProperty(organizationId,input as Required<Pick<PropertyInput,"slug"|"name"|"city"|"address"|"stars">>&PropertyInput,actor(request,context))});});
    app.patch<{Params:{id:string}}>(`${config.prefix}/hotels/:id`,async(request,reply)=>{const context=await contextFor(request,reply,config.scope,config.manage);if(!context||!valid([request.params.id],reply))return;protect(request,context);const parsed=updateProperty.safeParse(request.body);if(!parsed.success)return d.errorResponse(reply,400,"VALIDATION_ERROR","تغییرات هتل معتبر نیست");if(config.scope==="MERCHANT"&&parsed.data.publicationStatus&&!['DRAFT','SUBMITTED','PAUSED','ARCHIVED'].includes(parsed.data.publicationStatus))return d.errorResponse(reply,403,"APPROVAL_REQUIRED","انتشار هتل فقط توسط بک‌آفیس انجام می‌شود");return{property:await d.repository.updateProperty(request.params.id,parsed.data as PropertyInput,actor(request,context),config.scope==="MERCHANT"?context.organization.id:undefined)};});
    app.post<{Params:{id:string}}>(`${config.prefix}/hotels/:id/rooms`,async(request,reply)=>{const context=await contextFor(request,reply,config.scope,config.manage);if(!context||!valid([request.params.id],reply))return;protect(request,context);const parsed=roomSchema.safeParse(request.body);if(!parsed.success)return d.errorResponse(reply,400,"VALIDATION_ERROR","اطلاعات اتاق معتبر نیست");return reply.code(201).send({room:await d.repository.createRoom(request.params.id,parsed.data as RoomInput,actor(request,context),config.scope==="MERCHANT"?context.organization.id:undefined)});});
    app.patch<{Params:{id:string;roomId:string}}>(`${config.prefix}/hotels/:id/rooms/:roomId`,async(request,reply)=>{const context=await contextFor(request,reply,config.scope,config.manage);if(!context||!valid([request.params.id,request.params.roomId],reply))return;protect(request,context);const parsed=roomSchema.partial().refine(v=>Object.keys(v).length>0).safeParse(request.body);if(!parsed.success)return d.errorResponse(reply,400,"VALIDATION_ERROR","تغییرات اتاق معتبر نیست");return{room:await d.repository.updateRoom(request.params.id,request.params.roomId,parsed.data,actor(request,context),config.scope==="MERCHANT"?context.organization.id:undefined)};});
    app.post<{Params:{id:string;roomId:string}}>(`${config.prefix}/hotels/:id/rooms/:roomId/duplicate`,async(request,reply)=>{const context=await contextFor(request,reply,config.scope,config.manage);if(!context||!valid([request.params.id,request.params.roomId],reply))return;protect(request,context);return reply.code(201).send({room:await d.repository.duplicateRoom(request.params.id,request.params.roomId,actor(request,context),config.scope==="MERCHANT"?context.organization.id:undefined)});});
    app.post<{Params:{id:string;roomId:string}}>(`${config.prefix}/hotels/:id/rooms/:roomId/rates`,async(request,reply)=>{const context=await contextFor(request,reply,config.scope,config.manage);if(!context||!valid([request.params.id,request.params.roomId],reply))return;protect(request,context);const parsed=rateSchema.safeParse(request.body);if(!parsed.success)return d.errorResponse(reply,400,"VALIDATION_ERROR","اطلاعات نرخ معتبر نیست");return reply.code(201).send({rate:await d.repository.createRate(request.params.id,request.params.roomId,parsed.data as RateInput,actor(request,context),config.scope==="MERCHANT"?context.organization.id:undefined)});});
    app.patch<{Params:{id:string;rateId:string}}>(`${config.prefix}/hotels/:id/rates/:rateId`,async(request,reply)=>{const context=await contextFor(request,reply,config.scope,config.manage);if(!context||!valid([request.params.id,request.params.rateId],reply))return;protect(request,context);const parsed=rateSchema.partial().refine(v=>Object.keys(v).length>0).safeParse(request.body);if(!parsed.success)return d.errorResponse(reply,400,"VALIDATION_ERROR","تغییرات نرخ معتبر نیست");return{rate:await d.repository.updateRate(request.params.id,request.params.rateId,parsed.data,actor(request,context),config.scope==="MERCHANT"?context.organization.id:undefined)};});
    app.get<{Params:{id:string;rateId:string}}>(`${config.prefix}/hotels/:id/rates/:rateId/inventory`,async(request,reply)=>{const context=await contextFor(request,reply,config.scope,config.read);if(!context||!valid([request.params.id,request.params.rateId],reply))return;const parsed=z.object({from:z.coerce.date(),to:z.coerce.date()}).safeParse(request.query);if(!parsed.success)return d.errorResponse(reply,400,"VALIDATION_ERROR","بازه موجودی معتبر نیست");return{rate:await d.repository.inventory(request.params.id,request.params.rateId,parsed.data.from,parsed.data.to,config.scope==="MERCHANT"?context.organization.id:undefined)};});
    app.put<{Params:{id:string;rateId:string}}>(`${config.prefix}/hotels/:id/rates/:rateId/inventory`,async(request,reply)=>{const permission=config.scope==="MERCHANT"?"merchant.inventory.manage" as PermissionCode:config.manage;const context=await contextFor(request,reply,config.scope,permission);if(!context||!valid([request.params.id,request.params.rateId],reply))return;protect(request,context);const parsed=inventorySchema.safeParse(request.body);if(!parsed.success)return d.errorResponse(reply,400,"VALIDATION_ERROR","تغییر موجودی معتبر نیست");return await d.repository.bulkInventory(request.params.id,request.params.rateId,parsed.data as {from:Date;to:Date;weekdays?:number[];availableRooms?:number;priceOverride?:number|null;closed?:boolean;minimumStay?:number},actor(request,context),config.scope==="MERCHANT"?context.organization.id:undefined);});
  }
  app.get("/api/backoffice/hotel-bookings",async(request,reply)=>{const context=await contextFor(request,reply,"INTERNAL","backoffice.orders.read");if(!context)return;const filters=bookingFilters.safeParse(request.query);if(!filters.success)return d.errorResponse(reply,400,"VALIDATION_ERROR","فیلتر رزرو معتبر نیست");const page=pageOf(request.query);const result=await d.repository.bookings(page,filters.data);return{bookings:result.items,pagination:{...page,total:result.total,totalPages:Math.ceil(result.total/page.perPage)}};});
  app.get("/api/merchant/hotel-bookings",async(request,reply)=>{const context=await contextFor(request,reply,"MERCHANT","merchant.bookings.read");if(!context)return;const filters=bookingFilters.safeParse(request.query);if(!filters.success)return d.errorResponse(reply,400,"VALIDATION_ERROR","فیلتر رزرو معتبر نیست");const page=pageOf(request.query);const result=await d.repository.bookings(page,filters.data,context.organization.id);return{bookings:result.items,pagination:{...page,total:result.total,totalPages:Math.ceil(result.total/page.perPage)}};});
  app.get("/api/merchant/hotel-guests",async(request,reply)=>{const context=await contextFor(request,reply,"MERCHANT","merchant.guests.read");if(!context)return;const page=pageOf(request.query);const result=await d.repository.guests(page,context.organization.id);return{guests:result.items,pagination:{...page,total:result.total}};});
}
