import { Check, Edit3, Hotel as HotelIcon, Plane } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { BookingDraft, HotelBookingDraft } from '@/types/checkout';
import { calculateDraftPrice } from '@/services/checkout';
import { calculateNights } from '@/services/hotelService';
import { formatPrice, formatTime } from '@/utils/flight';

export const CheckoutStepper = ({ active, firstLabel = 'اطلاعات مسافران' }: { active: 1 | 2 | 3; firstLabel?: string }) => <div className="mb-6 rounded-2xl border border-border bg-card p-4 sm:p-5"><div className="flex items-center justify-between gap-1 sm:mx-auto sm:max-w-2xl">{[[firstLabel, 1], ['بررسی سفارش', 2], ['پرداخت', 3], ['تایید نهایی', 4]].map(([label, step], index) => <div key={String(label)} className="flex flex-1 items-center gap-1 last:flex-none"><div className={`flex items-center gap-2 ${Number(step) <= active ? 'text-primary' : 'text-muted-foreground'}`}><span className={`grid size-8 place-items-center rounded-full text-xs font-bold ${Number(step) < active ? 'bg-secondary text-white' : Number(step) === active ? 'bg-primary text-white' : 'bg-muted'}`}>{Number(step) < active ? <Check className="size-4" /> : step}</span><span className="hidden text-xs font-bold sm:block">{label}</span></div>{index < 3 && <span className="mx-1 h-px flex-1 bg-border" />}</div>)}</div></div>;

export const FlightSummary = ({ draft, compact = false }: { draft: BookingDraft; compact?: boolean }) => <div className="rounded-2xl border border-border bg-card p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-extrabold">خلاصه پرواز</h2><Link to={draft.searchUrl || '/flights/search'} className="inline-flex items-center gap-1 text-xs font-bold text-secondary"><Edit3 className="size-3.5" /> تغییر پرواز</Link></div>{[draft.outbound, draft.inbound].filter(Boolean).map((flight, index) => flight && <div key={flight.id} className={`flex items-center gap-3 ${index ? 'mt-3 border-t border-border pt-3' : ''}`}><span className="grid size-9 place-items-center rounded-lg bg-secondary/10 text-xs font-extrabold text-secondary">{flight.airlineCode}</span><div className="min-w-0 flex-1"><p className="text-sm font-bold">{index ? 'برگشت' : 'رفت'} · {flight.fromCity} ← {flight.toCity}</p><p className="text-xs text-muted-foreground">{formatTime(flight.departure)} تا {formatTime(flight.arrival)} · {flight.baggageKg} کیلو بار · {flight.cabin}</p>{!compact && <p className="mt-1 text-xs text-muted-foreground">{flight.refundable ? 'قابل استرداد با جریمه' : 'غیرقابل استرداد'} · {flight.flightNumber}</p>}</div></div>)}</div>;

export const HotelSummary = ({ draft }: { draft: HotelBookingDraft }) => { const nights = calculateNights(draft.hotelSearch.checkIn, draft.hotelSearch.checkOut); return <div className="rounded-2xl border border-border bg-card p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><div className="flex items-center gap-2"><HotelIcon className="size-5 text-secondary" /><h2 className="font-extrabold">خلاصه اقامت</h2></div><Link to={draft.searchUrl} className="inline-flex items-center gap-1 text-xs font-bold text-secondary"><Edit3 className="size-3.5" /> تغییر اتاق</Link></div><div className="flex gap-3"><img src={draft.hotel.images[0]} alt={draft.hotel.name} className="size-20 rounded-lg object-cover" /><div><p className="text-sm font-extrabold">{draft.hotel.name}</p><p className="mt-1 text-xs text-muted-foreground">{draft.hotel.city} · {draft.hotelRoom.name}</p><p className="mt-2 text-xs">{draft.hotelSearch.checkIn} تا {draft.hotelSearch.checkOut} · {nights.toLocaleString('fa-IR')} شب</p><p className="mt-1 text-xs text-muted-foreground">{draft.roomCount.toLocaleString('fa-IR')} اتاق · {draft.hotelRatePlan.title}</p></div></div></div>; };

export const BookingSummary = ({ draft, compact = false }: { draft: BookingDraft; compact?: boolean }) => draft.serviceType === 'hotel' ? <HotelSummary draft={draft as HotelBookingDraft} /> : <FlightSummary draft={draft} compact={compact} />;
export const PriceSummary = ({ draft, onCoupon }: { draft: BookingDraft; onCoupon?: () => void }) => { const p = calculateDraftPrice(draft); const isHotel = draft.serviceType === 'hotel'; return <div className="rounded-2xl border border-border bg-card p-4 sm:p-5"><h2 className="mb-4 font-extrabold">خلاصه هزینه</h2><div className="space-y-3 text-sm">{isHotel ? <><div className="flex justify-between"><span>اتاق و اقامت</span><span>{formatPrice(p.passengers)}</span></div><div className="flex justify-between text-muted-foreground"><span>تعداد اتاق</span><span>{(draft as HotelBookingDraft).roomCount.toLocaleString('fa-IR')} اتاق</span></div></> : <><div className="flex justify-between"><span>پرواز رفت</span><span>{formatPrice(p.outbound)}</span></div>{p.inbound > 0 && <div className="flex justify-between"><span>پرواز برگشت</span><span>{formatPrice(p.inbound)}</span></div>}<div className="flex justify-between text-muted-foreground"><span>تعداد مسافر</span><span>{draft.passengers.length} نفر</span></div></>}{p.ancillaries > 0 && <div className="flex justify-between text-muted-foreground"><span>خدمات انتخابی</span><span>{formatPrice(p.ancillaries)}</span></div>}{p.discount > 0 && <div className="flex justify-between text-secondary"><span>تخفیف {draft.coupon?.code}</span><span>− {formatPrice(p.discount)}</span></div>}<div className="flex justify-between border-t border-border pt-3 text-base font-extrabold"><span>مبلغ نهایی</span><span className="text-primary">{formatPrice(p.total)}</span></div></div>{onCoupon && <button type="button" onClick={onCoupon} className="mt-4 w-full rounded-lg border border-border py-2.5 text-xs font-bold hover:border-secondary">کد تخفیف دارید؟</button>}<p className="mt-3 text-[11px] leading-5 text-muted-foreground">قیمت‌ها و خدمات برای نسخهٔ آزمایشی نمایش داده می‌شوند.</p></div>; };
export const EmptyCheckout = () => <div className="container-page flex min-h-[65vh] items-center justify-center py-14"><div className="max-w-md rounded-2xl border border-border bg-card p-8 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-secondary/10 text-secondary"><Plane className="size-7" /></span><h1 className="mt-5 text-xl font-extrabold">برای ادامه رزرو ابتدا یک سفر انتخاب کنید.</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">انتخاب شما در این مرورگر پیدا نشد.</p><div className="mt-6 flex justify-center gap-2"><Link to="/" className="rounded-lg bg-primary px-4 py-3 text-sm font-bold text-primary-foreground">شروع جستجو</Link></div></div></div>;
