import { Check, Edit3, Plane, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';
import type { BookingDraft } from '@/types/checkout';
import { calculatePrice } from '@/services/checkout';
import { formatPrice, formatTime } from '@/utils/flight';

export const CheckoutStepper = ({ active }: { active: 1 | 2 | 3 }) => <div className="mb-6 rounded-2xl border border-border bg-card p-4 sm:p-5"><div className="flex items-center justify-between gap-1 sm:mx-auto sm:max-w-2xl">{[['اطلاعات مسافران', 1], ['بررسی سفارش', 2], ['پرداخت', 3], ['تایید نهایی', 4]].map(([label, step], index) => <div key={String(label)} className="flex flex-1 items-center gap-1 last:flex-none"><div className={`flex items-center gap-2 ${Number(step) <= active ? 'text-primary' : 'text-muted-foreground'}`}><span className={`grid size-8 place-items-center rounded-full text-xs font-bold ${Number(step) < active ? 'bg-secondary text-white' : Number(step) === active ? 'bg-primary text-white' : 'bg-muted'}`}>{Number(step) < active ? <Check className="size-4" /> : step}</span><span className="hidden text-xs font-bold sm:block">{label}</span></div>{index < 3 && <span className="mx-1 h-px flex-1 bg-border" />}</div>)}</div></div>;
export const FlightSummary = ({ draft, compact = false }: { draft: BookingDraft; compact?: boolean }) => <div className="rounded-2xl border border-border bg-card p-4 sm:p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-extrabold">خلاصه پرواز</h2><Link to={draft.searchUrl || '/flights/search'} className="inline-flex items-center gap-1 text-xs font-bold text-secondary"><Edit3 className="size-3.5" /> تغییر پرواز</Link></div>{[draft.outbound, draft.inbound].filter(Boolean).map((flight, index) => flight && <div key={flight.id} className={`flex items-center gap-3 ${index ? 'mt-3 border-t border-border pt-3' : ''}`}><span className="grid size-9 place-items-center rounded-lg bg-secondary/10 text-xs font-extrabold text-secondary">{flight.airlineCode}</span><div className="min-w-0 flex-1"><p className="text-sm font-bold">{index ? 'برگشت' : 'رفت'} · {flight.fromCity} ← {flight.toCity}</p><p className="text-xs text-muted-foreground">{formatTime(flight.departure)} تا {formatTime(flight.arrival)} · {flight.baggageKg} کیلو بار · {flight.cabin}</p>{!compact && <p className="mt-1 text-xs text-muted-foreground">{flight.refundable ? 'قابل استرداد با جریمه' : 'غیرقابل استرداد'} · {flight.flightNumber}</p>}</div></div>)}</div>;
export const PriceSummary = ({ draft, onCoupon }: { draft: BookingDraft; onCoupon?: () => void }) => { const p = calculatePrice(draft.outbound, draft.inbound, draft.passengers, draft.ancillaries, draft.coupon); return <div className="rounded-2xl border border-border bg-card p-4 sm:p-5"><h2 className="mb-4 font-extrabold">خلاصه هزینه</h2><div className="space-y-3 text-sm"><div className="flex justify-between"><span>پرواز رفت</span><span>{formatPrice(p.outbound)}</span></div>{p.inbound > 0 && <div className="flex justify-between"><span>پرواز برگشت</span><span>{formatPrice(p.inbound)}</span></div>}<div className="flex justify-between text-muted-foreground"><span>تعداد مسافر</span><span>{draft.passengers.length} نفر</span></div>{p.ancillaries > 0 && <div className="flex justify-between text-muted-foreground"><span>خدمات انتخابی</span><span>{formatPrice(p.ancillaries)}</span></div>}{p.discount > 0 && <div className="flex justify-between text-secondary"><span>تخفیف {draft.coupon?.code}</span><span>− {formatPrice(p.discount)}</span></div>}<div className="flex justify-between border-t border-border pt-3 text-base font-extrabold"><span>مبلغ نهایی</span><span className="text-primary">{formatPrice(p.total)}</span></div></div>{onCoupon && <button type="button" onClick={onCoupon} className="mt-4 w-full rounded-lg border border-border py-2.5 text-xs font-bold hover:border-secondary">کد تخفیف دارید؟</button>}<p className="mt-3 text-[11px] leading-5 text-muted-foreground">قیمت‌ها و خدمات برای نسخهٔ آزمایشی نمایش داده می‌شوند.</p></div>; };
export const EmptyCheckout = () => <div className="container-page flex min-h-[65vh] items-center justify-center py-14"><div className="max-w-md rounded-2xl border border-border bg-card p-8 text-center"><span className="mx-auto grid size-14 place-items-center rounded-2xl bg-secondary/10 text-secondary"><Plane className="size-7" /></span><h1 className="mt-5 text-xl font-extrabold">برای ادامه رزرو ابتدا یک پرواز انتخاب کنید.</h1><p className="mt-2 text-sm leading-6 text-muted-foreground">انتخاب پرواز شما در این مرورگر پیدا نشد.</p><div className="mt-6 flex justify-center gap-2"><Link to="/flights/search?from=IKA&to=IST&departure=2026-10-12&adults=1&trip=oneway" className="rounded-lg bg-primary px-4 py-3 text-sm font-bold text-primary-foreground">جستجوی پرواز</Link><Link to="/" className="rounded-lg border border-border px-4 py-3 text-sm font-bold">صفحه اصلی</Link></div></div></div>;
