export type SecondaryType = 'train' | 'bus' | 'insurance' | 'cip' | 'transfer';
export interface TrainOffer { id:string; company:string; trainName:string; trainNumber:string; origin:string; destination:string; departure:string; arrival:string; duration:string; coachType:string; compartmentType:string; stars:number; amenities:string[]; meal:boolean; refundable:boolean; price:number; currency:'IRR'; tags:string[]; }
export interface BusOffer { id:string; company:string; busType:'VIP'|'معمولی'; origin:string; destination:string; originTerminal:string; destinationTerminal:string; departure:string; arrivalEstimated:string; duration:string; seatLayout:string; availableSeatsMock:number; amenities:string[]; price:number; currency:'IRR'; refundable:boolean; tags:string[]; }
export interface InsurancePlan { id:string; providerMock:string; name:string; coverageLimitMock:string; medicalSummaryMock:string; baggageSummaryMock:string; tripDelaySummaryMock:string; duration:string; price:number; currency:'IRR'; featured:boolean; termsMock:string; }
export interface CipPackage { id:string; name:string; description:string; includes:string[]; price:number; currency:'IRR'; }
export interface TransferVehicle { id:string; name:string; capacity:number; luggage:number; features:string[]; price:number; icon:string; }
export type SecondaryItem = TrainOffer | BusOffer | InsurancePlan | CipPackage | TransferVehicle;
export interface SecondaryTraveler { id:string; firstName:string; lastName:string; birthDate:string; nationalId:string; }
export interface SecondaryCheckoutDraft { serviceType: SecondaryType; secondaryType: SecondaryType; item: SecondaryItem; query: Record<string,string>; quantity:number; selectedSeats?:string[]; buyer: { firstName:string; lastName:string; mobile:string; email:string }; travelers: SecondaryTraveler[]; addOns:string[]; }
export interface VisaApplication { id:string; userId?:string; country:string; visaType:string; applicant:{ firstName:string; lastName:string; mobile:string; email:string; nationality:string; passportNumber:string; passportExpiry:string; birthDate:string }; travel:{ departure:string; returnDate:string; purpose:string; notes:string }; documents:{ name:string; size:number; type:string }[]; status:'submitted'|'documents_required'|'under_review'|'approved_mock'|'rejected_mock'; createdAt:string; updatedAt:string; notes:string; serviceFee:number; trackingNumber:string; }
