import { CalendarDays, Hotel, Plane, TrainFront, Bus, Compass } from 'lucide-react';
import { Link } from 'react-router-dom';
import Layout from '@/components/layout/Layout';
import { AccountLayout } from '@/components/account/AccountLayout';
import { useAuth } from '@/context/AuthContext';
import { listOrdersForUser } from '@/services/payment';
import { secondaryLabel } from '@/services/secondaryService';
import { formatPrice } from '@/utils/flight';

const iconFor=(type:string|undefined)=>type==='hotel'?Hotel:type==='train'?TrainFront:type==='bus'?Bus:type==='tour'||type==='ziyarat'?Compass:Plane;
export default function AccountTrips(){const {user}=useAuth();const orders=user?listOrdersForUser(user.id):[];const today=Date.now();const upcoming=orders.filter((order)=>new Date(order.createdAt).getTime()>=today-86400000*30);const past=orders.filter((order)=>!upcoming.includes(order));const Card=({items,title}:{items:typeof orders;title:string})=><section className="rounded-2xl border border-border bg-card p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-extrabold">{title}</h2><span className="rounded-full bg-muted px-2.5 py-1 text-xs font-bold">{items.length} سفر</span></div>{items.length?<div className="space-y-3">{items.map((order)=>{const Icon=iconFor(order.serviceType);const secondary=order.secondarySnapshot;const label=secondary?secondaryLabel(secondary.type):order.serviceType==='hotel'?'هتل':order.serviceType==='tour'?'تور':order.serviceType==='ziyarat'?'زیارت':'پرواز';return <Link to={`/account/orders/${order.id}`} key={order.id} className="flex items-center gap-3 rounded-xl border border-border p-4 hover:border-secondary"><span className="grid size-10 place-items-center rounded-lg bg-secondary/10 text-secondary"><Icon className="size-5"/></span><div className="min-w-0 flex-1"><p className="text-xs text-muted-foreground">{label} · {order.orderNumber}</p><p className="mt-1 truncate font-bold">{secondary?('name' in secondary.item?secondary.item.name:'trainName' in secondary.item?secondary.item.trainName:secondary.item.company):order.hotelSnapshot?.hotel.name||order.experienceSnapshot?.offer.title||`${order.outbound?.fromCity||'مبدأ'} ← ${order.outbound?.toCity||'مقصد'}`}</p><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><CalendarDays className="size-3.5"/> {new Date(order.createdAt).toLocaleDateString('fa-IR')} · {formatPrice(order.pricing.total)}</p></div><span className="text-xs font-bold text-secondary">جزئیات ←</span></Link>})}</div>:<p className="py-8 text-center text-sm text-muted-foreground">هنوز سفری در این بخش ندارید.</p>}</section>;return <Layout><AccountLayout><div className="space-y-5"><div><p className="text-xs font-bold text-primary">Travel Center</p><h2 className="mt-1 text-2xl font-extrabold">سفرهای من</h2><p className="mt-2 text-sm text-muted-foreground">همه رزروهای پرواز، هتل، تور، قطار، اتوبوس و خدمات سفر را یکجا ببینید.</p></div><Card items={upcoming} title="سفرهای پیش رو"/><Card items={past} title="سفرهای گذشته"/></div></AccountLayout></Layout>}
