import { ArrowLeft, ArrowUpLeft, BadgeCheck, BusFront, CalendarDays, Car, ChevronLeft, CircleHelp, Compass, Headphones, Hotel as HotelIcon, MapPinned, Plane, ShieldCheck, Star, TrainFront, Umbrella, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import { featuredHotels, featuredTours, offers, popularDestinations, popularRoutes, travelArticles, ziyaratOptions } from '@/data/homepage';
import type { Hotel, Tour } from '@/types/travel';

const price = (value: number) => new Intl.NumberFormat('fa-IR').format(Math.round(value / 1000) * 1000);
const SectionHeading = ({ eyebrow, title, href, action = 'مشاهده همه' }: { eyebrow?: string; title: string; href?: string; action?: string }) => <div className="mb-6 flex items-end justify-between gap-4"><div>{eyebrow && <p className="mb-2 text-xs font-semibold text-primary">{eyebrow}</p>}<h2 className="text-2xl font-extrabold tracking-tight sm:text-3xl">{title}</h2></div>{href && <Link to={href} className="hidden shrink-0 items-center gap-1 text-sm font-bold text-secondary hover:text-primary sm:inline-flex">{action}<ArrowLeft className="size-4" /></Link>}</div>;

export const RecentSearches = () => <section className="container-page py-8"><div className="flex flex-wrap items-center gap-3"><span className="text-sm font-bold">جستجوهای اخیر</span><button type="button" className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-sm hover:border-secondary"><Plane className="size-4 text-secondary" /><span>تهران <span className="text-muted-foreground">←</span> استانبول</span><span className="text-xs text-muted-foreground">۲ مسافر</span></button><button type="button" className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-sm hover:border-secondary"><HotelIcon className="size-4 text-secondary" /><span>هتل‌های کیش</span><span className="text-xs text-muted-foreground">۲ شب</span></button><Link to="/destinations" className="inline-flex items-center gap-1 text-sm font-semibold text-primary">مقصدهای محبوب <ArrowLeft className="size-4" /></Link></div></section>;

export const OffersSection = () => <section className="container-page section-space"><SectionHeading eyebrow="پیشنهادهای کی‌آشی" title="برای سفر بعدی‌ات آماده‌ای؟" href="/tours" /><div className="grid gap-4 md:grid-cols-3">{offers.map((offer) => <Link key={offer.id} to={offer.href} className="group relative min-h-56 overflow-hidden rounded-2xl"><img src={offer.image} alt={offer.title} className="absolute inset-0 size-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/20 to-transparent" /><div className="relative flex h-full flex-col justify-end p-5 text-white"><span className={`mb-3 inline-flex w-fit rounded-md px-2 py-1 text-[11px] font-bold ${offer.accent}`}>پیشنهاد ویژه</span><h3 className="text-xl font-extrabold">{offer.title}</h3><p className="mt-1 text-sm text-white/80">{offer.description}</p><span className="mt-3 inline-flex items-center gap-1 text-xs font-bold">مشاهده پیشنهاد <ArrowLeft className="size-3.5" /></span></div></Link>)}</div></section>;

export const RoutesSection = () => <section className="bg-muted/60"><div className="container-page section-space"><SectionHeading eyebrow="انتخاب‌های محبوب مسافران" title="مسیرهای پرطرفدار" href="/flights" /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{popularRoutes.map((route) => <Link key={route.id} to={`/flights/search?from=${route.from}&to=${route.to}`} className="surface-card group flex items-center justify-between p-4 transition hover:-translate-y-0.5 hover:border-secondary"><div><p className="text-sm font-bold">{route.from} <span className="mx-1 text-secondary">←</span> {route.to}</p><p className="mt-1 text-xs text-muted-foreground">{route.hint}</p></div><div className="text-end"><p className="text-xs font-semibold text-primary">{route.price}</p><ArrowLeft className="mt-2 ms-auto size-4 text-muted-foreground transition group-hover:text-secondary" /></div></Link>)}</div></div></section>;

const TourCard = ({ tour }: { tour: Tour }) => <Link to={`/tours/${tour.id}`} className="group overflow-hidden rounded-2xl border border-border bg-card"><div className="relative aspect-[1.45] overflow-hidden"><img src={tour.imageUrl} alt={tour.title} className="size-full object-cover transition duration-500 group-hover:scale-105" /><span className="absolute start-3 top-3 rounded-md bg-card/90 px-2 py-1 text-xs font-bold">{tour.durationDays} شب</span></div><div className="p-4"><p className="text-xs text-muted-foreground">{tour.destination}</p><h3 className="mt-1 font-bold">{tour.title}</h3><div className="mt-3 flex flex-wrap gap-2">{tour.services.map((service) => <span key={service.title} className="rounded-md bg-muted px-2 py-1 text-[11px] text-muted-foreground">{service.title}</span>)}</div><div className="mt-4 flex items-end justify-between border-t border-border pt-3"><div><span className="text-[11px] text-muted-foreground">شروع قیمت</span><p className="font-extrabold text-primary">{price(tour.dates[0]?.price ?? 0)} <small className="text-[10px] font-normal">تومان</small></p></div><span className="grid size-8 place-items-center rounded-lg bg-primary/10 text-primary"><ArrowLeft className="size-4" /></span></div></div></Link>;
export const ToursSection = () => <section className="container-page section-space"><SectionHeading eyebrow="با خیال راحت برنامه‌ریزی کن" title="تورهای منتخب" href="/tours" /> <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{featuredTours.map((tour) => <TourCard key={tour.id} tour={tour} />)}</div></section>;

const HotelCard = ({ hotel }: { hotel: Hotel }) => <Link to={`/hotels/${hotel.id}`} className="group overflow-hidden rounded-2xl border border-border bg-card"><div className="relative aspect-[1.45] overflow-hidden"><img src={hotel.imageUrl} alt={hotel.name} className="size-full object-cover transition duration-500 group-hover:scale-105" /><span className="absolute start-3 top-3 inline-flex items-center gap-1 rounded-md bg-card/90 px-2 py-1 text-xs font-bold text-warning"><Star className="size-3 fill-current" />{hotel.rating}</span></div><div className="p-4"><div className="flex items-center justify-between gap-3"><div><h3 className="font-bold">{hotel.name}</h3><p className="mt-1 text-xs text-muted-foreground">{hotel.city}، {hotel.country}</p></div><span className="text-xs text-muted-foreground">{hotel.reviewCount} نظر</span></div><div className="mt-3 flex flex-wrap gap-2">{hotel.amenities.map((amenity) => <span key={amenity.id} className="rounded-md bg-muted px-2 py-1 text-[11px] text-muted-foreground">{amenity.name}</span>)}</div><div className="mt-4 border-t border-border pt-3"><span className="text-[11px] text-muted-foreground">هر شب از</span><p className="font-extrabold text-primary">{price(hotel.rooms[0]?.rates[0]?.amount ?? 2400000)} <small className="text-[10px] font-normal">تومان</small></p></div></div></Link>;
export const HotelsSection = () => <section className="bg-muted/60"><div className="container-page section-space"><SectionHeading eyebrow="اقامت باکیفیت" title="هتل‌های پیشنهادی" href="/hotels" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{featuredHotels.map((hotel) => <HotelCard key={hotel.id} hotel={hotel} />)}</div></div></section>;

export const DestinationsSection = () => <section className="container-page section-space"><SectionHeading eyebrow="الهام بگیر و انتخاب کن" title="مقصدهای محبوب" href="/destinations" /><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{popularDestinations.map((destination) => <Link key={destination.id} to={`/destinations/${destination.slug}`} className="group relative aspect-[0.82] overflow-hidden rounded-2xl"><img src={destination.imageUrl} alt={destination.name} className="absolute inset-0 size-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/10 to-transparent" /><div className="relative flex h-full flex-col justify-end p-3 text-white"><p className="text-[10px] text-white/75">{destination.country}</p><h3 className="mt-0.5 font-bold">{destination.name}</h3><p className="mt-1 hidden text-[10px] text-white/75 sm:block">{destination.description}</p></div></Link>)}</div></section>;

export const ZiyaratSection = () => <section className="bg-[hsl(177_31%_18%)] text-white"><div className="container-page section-space"><div className="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="mb-2 text-xs font-semibold text-[hsl(42_100%_60%)]">سفر با آرامش و احترام</p><h2 className="text-2xl font-extrabold sm:text-3xl">سفرهای زیارتی</h2><p className="mt-2 max-w-lg text-sm leading-7 text-white/65">برنامه‌های نمونه برای زیارت نجف، کربلا و مقصدهای معنوی؛ با اطلاعات شفاف و قابل مقایسه.</p></div><Link to="/ziyarat" className="inline-flex items-center gap-1 text-sm font-bold text-[hsl(42_100%_60%)]">مشاهده همه برنامه‌ها <ArrowLeft className="size-4" /></Link></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{ziyaratOptions.map((option) => <Link key={option.id} to="/ziyarat" className="rounded-xl border border-white/10 bg-white/5 p-4 transition hover:bg-white/10"><div className="mb-5 flex items-center justify-between"><Compass className="size-5 text-[hsl(42_100%_60%)]" /><span className="text-xs text-white/55">{option.type}</span></div><h3 className="font-bold">{option.title}</h3><p className="mt-2 text-xs text-white/60">{option.duration} · {option.date}</p><p className="mt-4 text-sm font-bold text-[hsl(42_100%_60%)]">{option.price}</p></Link>)}</div></div></section>;

const services = [{ title: 'ویزا', text: 'راهنمایی و پیگیری درخواست ویزا', icon: MapPinned, to: '/visa' }, { title: 'بیمه مسافرتی', text: 'پوشش مناسب برای سفرهای داخلی و خارجی', icon: Umbrella, to: '/insurance' }, { title: 'CIP فرودگاهی', text: 'تجربه‌ای راحت‌تر در فرودگاه', icon: Plane, to: '/cip' }, { title: 'ترانسفر', text: 'رفت‌وآمد مطمئن در مقصد', icon: Car, to: '/transfers' }, { title: 'گشت شهری', text: 'مقصد را مثل یک محلی ببین', icon: Compass, to: '/tours' }, { title: 'پشتیبانی سفر', text: 'همراهت هستیم، قبل و بعد از سفر', icon: Headphones, to: '/support' }];
export const ServicesSection = () => <section className="container-page section-space"><SectionHeading eyebrow="همه‌چیز برای یک سفر خوب" title="خدمات سفر" /><div className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{services.map(({ title, text, icon: Icon, to }) => <Link key={title} to={to} className="rounded-xl border border-border bg-card p-4 transition hover:-translate-y-1 hover:border-secondary hover:shadow-md"><span className="grid size-10 place-items-center rounded-xl bg-secondary/10 text-secondary"><Icon className="size-5" /></span><h3 className="mt-4 text-sm font-bold">{title}</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">{text}</p></Link>)}</div></section>;

export const TrustSection = () => <section className="bg-primary/5"><div className="container-page section-space"><div className="grid gap-8 lg:grid-cols-[1fr_2fr] lg:items-center"><div><p className="mb-2 text-xs font-semibold text-primary">چرا کی‌آشی؟</p><h2 className="text-2xl font-extrabold sm:text-3xl">سفر را با اطمینان شروع کن</h2><p className="mt-3 max-w-md text-sm leading-7 text-muted-foreground">ما ابزارهای ساده و شفاف برای مقایسه و برنامه‌ریزی سفر را کنار هم آورده‌ایم تا انتخاب‌کردن راحت‌تر شود.</p></div><div className="grid gap-3 sm:grid-cols-2"><div className="surface-card p-5"><ShieldCheck className="size-6 text-secondary" /><h3 className="mt-3 font-bold">رزرو ساده و شفاف</h3><p className="mt-1 text-sm text-muted-foreground">اطلاعات مهم را واضح می‌بینی و با چند قدم انتخاب می‌کنی.</p></div><div className="surface-card p-5"><UsersRound className="size-6 text-primary" /><h3 className="mt-3 font-bold">پشتیبانی در مسیر</h3><p className="mt-1 text-sm text-muted-foreground">برای سوال‌های قبل و بعد از رزرو، مسیر ارتباط مشخص است.</p></div><div className="surface-card p-5"><BadgeCheck className="size-6 text-warning" /><h3 className="mt-3 font-bold">مقایسهٔ گزینه‌ها</h3><p className="mt-1 text-sm text-muted-foreground">پرواز، هتل و تور را با جزئیات قابل فهم کنار هم ببین.</p></div><div className="surface-card p-5"><CircleHelp className="size-6 text-secondary" /><h3 className="mt-3 font-bold">راهنمای سفر</h3><p className="mt-1 text-sm text-muted-foreground">مقاله‌ها و پیشنهادهای کاربردی برای تصمیم بهتر.</p></div></div></div></div></section>;

export const ArticlesSection = () => <section className="container-page section-space"><SectionHeading eyebrow="قبل از حرکت بخوان" title="الهام برای سفر" href="/blog" /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{travelArticles.map((article) => <Link key={article.id} to={`/blog/${article.id}`} className="group overflow-hidden rounded-2xl border border-border bg-card"><div className="aspect-[1.35] overflow-hidden"><img src={article.image} alt={article.title} className="size-full object-cover transition duration-500 group-hover:scale-105" /></div><div className="p-4"><p className="text-xs font-semibold text-primary">{article.category}</p><h3 className="mt-2 line-clamp-2 font-bold leading-6">{article.title}</h3><div className="mt-4 flex items-center justify-between text-xs text-muted-foreground"><span>{article.readingTime} مطالعه</span><ArrowLeft className="size-4 transition group-hover:text-primary" /></div></div></Link>)}</div></section>;

export const SupportSection = () => <section className="container-page pb-16"><div className="relative overflow-hidden rounded-2xl bg-secondary p-7 text-white sm:p-10"><div className="absolute -end-8 -top-16 size-48 rounded-full border-[24px] border-white/10" /><div className="relative flex flex-col justify-between gap-6 sm:flex-row sm:items-center"><div><p className="text-sm font-semibold text-white/70">همراهت هستیم</p><h2 className="mt-2 text-2xl font-extrabold">برای برنامه‌ریزی سفرت سوال داری؟</h2><p className="mt-2 text-sm text-white/75">راهنمایی‌های ساده را در مرکز راهنما بخوان یا با تیم پشتیبانی در تماس باش.</p></div><div className="flex flex-wrap gap-2"><Link to="/support" className="inline-flex items-center gap-2 rounded-lg bg-white px-4 py-3 text-sm font-bold text-secondary hover:bg-white/90"><Headphones className="size-4" /> پشتیبانی</Link><Link to="/faq" className="inline-flex items-center gap-2 rounded-lg border border-white/30 px-4 py-3 text-sm font-bold hover:bg-white/10"><CircleHelp className="size-4" /> مرکز راهنما</Link></div></div></div></section>;
