import { Prisma, PrismaClient } from "@prisma/client";
import { DomainError, notFound } from "../domain/errors.js";
import { assertManualInventoryAllowed, dateRange, maskGuestMobile, type HotelSourceType } from "../hotels/domain.js";
import { sanitizeProviderPayload } from "../providers/redaction.js";
import type { AuditActor, PageInput } from "./platform.js";

const asJson = (value: unknown) => value as Prisma.InputJsonValue;
const propertyInclude = { organization: { select: { id: true, name: true } }, roomTypes: { orderBy: { createdAt: "asc" as const }, include: { ratePlans: { orderBy: { createdAt: "asc" as const } } } }, _count: { select: { orders: true } } } satisfies Prisma.PropertyInclude;
export type PropertyInput = { slug?: string; name?: string; city?: string; country?: string; address?: string; area?: string | null; latitude?: number | null; longitude?: number | null; stars?: number; description?: string; checkInTime?: string; checkOutTime?: string; sourceType?: HotelSourceType; supplierCode?: string | null; publicationStatus?: string; operationalStatus?: string; amenities?: string[]; policies?: Record<string, unknown>; images?: string[] };
export type RoomInput = { name: string; description: string; capacity: number; bedType: string; sizeSqm?: number | null; amenities?: string[]; images?: string[]; status?: "ACTIVE" | "INACTIVE" };
export type RateInput = { title: string; mealPlan: string; refundable: boolean; cancellationPolicy: string; baseRate: number; currency?: string; taxesIncluded?: boolean; status?: "ACTIVE" | "INACTIVE" };

export class HotelRepository {
  constructor(private readonly prisma: PrismaClient) {}
  private audit(tx: Prisma.TransactionClient, actor: AuditActor, input: { action: string; resourceType: string; resourceId?: string; targetOrganizationId: string; beforeData?: unknown; afterData?: unknown }) { return tx.auditLog.create({ data: { actorUserId: actor.userId, actorOrganizationId: actor.organizationId, targetOrganizationId: input.targetOrganizationId, action: input.action, resourceType: input.resourceType, resourceId: input.resourceId, beforeData: input.beforeData === undefined ? undefined : asJson(sanitizeProviderPayload(input.beforeData)), afterData: input.afterData === undefined ? undefined : asJson(sanitizeProviderPayload(input.afterData)), requestId: actor.requestId, ipAddress: actor.ipAddress, userAgent: actor.userAgent?.slice(0, 500) } }); }
  private async owned(propertyId: string, organizationId?: string) { const property = await this.prisma.property.findFirst({ where: { id: propertyId, organizationId }, include: propertyInclude }); if (!property) throw notFound("هتل پیدا نشد"); return property; }

  async listProperties(page: PageInput, filters: { city?: string; sourceType?: string; publicationStatus?: string; search?: string }, organizationId?: string) {
    const where: Prisma.PropertyWhereInput = { organizationId, city: filters.city, sourceType: filters.sourceType, publicationStatus: filters.publicationStatus, ...(filters.search ? { OR: [{ name: { contains: filters.search, mode: "insensitive" } }, { slug: { contains: filters.search, mode: "insensitive" } }] } : {}) };
    const [items, total] = await Promise.all([this.prisma.property.findMany({ where, include: propertyInclude, orderBy: { updatedAt: "desc" }, skip: (page.page - 1) * page.perPage, take: page.perPage }), this.prisma.property.count({ where })]);
    const ids = items.map((item) => item.id); const now = new Date();
    const upcoming = ids.length ? await this.prisma.order.groupBy({ by: ["propertyId"], where: { propertyId: { in: ids }, paymentStatus: "paid", relevantDate: { gte: now } }, _count: { _all: true } }) : [];
    const counts = new Map(upcoming.map((entry) => [entry.propertyId, entry._count._all]));
    return { items: items.map((item) => ({ ...item, upcomingBookings: counts.get(item.id) ?? 0 })), total };
  }
  getProperty(id: string, organizationId?: string) { return this.owned(id, organizationId); }
  async createProperty(organizationId: string, input: Required<Pick<PropertyInput, "slug" | "name" | "city" | "address" | "stars">> & PropertyInput, actor: AuditActor) {
    return this.prisma.$transaction(async (tx) => { const merchant = await tx.organization.findFirst({ where: { id: organizationId, type: "MERCHANT", status: "ACTIVE", merchantProfile: { businessType: "HOTEL" } } }); if (!merchant) throw new DomainError("HOTEL_MERCHANT_REQUIRED", "پذیرنده هتل معتبر نیست", 409); const property = await tx.property.create({ data: { organizationId, slug: input.slug, name: input.name, city: input.city, country: input.country ?? "ایران", address: input.address, area: input.area, latitude: input.latitude, longitude: input.longitude, stars: input.stars, description: input.description ?? "", checkInTime: input.checkInTime ?? "14:00", checkOutTime: input.checkOutTime ?? "12:00", sourceType: input.sourceType ?? "DIRECT", supplierCode: input.supplierCode, amenities: input.amenities ? asJson(input.amenities) : undefined, policies: input.policies ? asJson(input.policies) : undefined, images: input.images ? asJson(input.images) : undefined }, include: propertyInclude }); await this.audit(tx, actor, { action: "property.created", resourceType: "Property", resourceId: property.id, targetOrganizationId: organizationId, afterData: { slug: property.slug, sourceType: property.sourceType } }); return property; });
  }
  async updateProperty(id: string, input: PropertyInput, actor: AuditActor, organizationId?: string) { return this.prisma.$transaction(async (tx) => { const current = await tx.property.findFirst({ where: { id, organizationId } }); if (!current) throw notFound("هتل پیدا نشد"); if (input.sourceType && input.sourceType !== current.sourceType && current.sourceType === "SUPPLIER") throw new DomainError("SOURCE_TYPE_LOCKED", "تغییر منبع هتل تأمین‌کننده نیازمند عملیات mapping است", 409); const property = await tx.property.update({ where: { id }, data: { ...input, latitude: input.latitude, longitude: input.longitude, amenities: input.amenities ? asJson(input.amenities) : undefined, policies: input.policies ? asJson(input.policies) : undefined, images: input.images ? asJson(input.images) : undefined }, include: propertyInclude }); await this.audit(tx, actor, { action: input.publicationStatus ? "property.publication.changed" : "property.updated", resourceType: "Property", resourceId: id, targetOrganizationId: current.organizationId, beforeData: { publicationStatus: current.publicationStatus }, afterData: { publicationStatus: property.publicationStatus } }); return property; }); }
  async createRoom(propertyId: string, input: RoomInput, actor: AuditActor, organizationId?: string) { return this.prisma.$transaction(async (tx) => { const property = await tx.property.findFirst({ where: { id: propertyId, organizationId } }); if (!property) throw notFound("هتل پیدا نشد"); const room = await tx.roomType.create({ data: { propertyId, ...input, amenities: input.amenities ? asJson(input.amenities) : undefined, images: input.images ? asJson(input.images) : undefined } }); await this.audit(tx, actor, { action: "room.created", resourceType: "RoomType", resourceId: room.id, targetOrganizationId: property.organizationId, afterData: { name: room.name, capacity: room.capacity } }); return room; }); }
  async updateRoom(propertyId: string, roomId: string, input: Partial<RoomInput>, actor: AuditActor, organizationId?: string) { return this.prisma.$transaction(async (tx) => { const current = await tx.roomType.findFirst({ where: { id: roomId, propertyId, property: { organizationId } }, include: { property: true } }); if (!current) throw notFound("اتاق پیدا نشد"); const room = await tx.roomType.update({ where: { id: roomId }, data: { ...input, amenities: input.amenities ? asJson(input.amenities) : undefined, images: input.images ? asJson(input.images) : undefined } }); await this.audit(tx, actor, { action: "room.updated", resourceType: "RoomType", resourceId: roomId, targetOrganizationId: current.property.organizationId, beforeData: { status: current.status }, afterData: { status: room.status } }); return room; }); }
  async duplicateRoom(propertyId: string, roomId: string, actor: AuditActor, organizationId?: string) { const current = await this.prisma.roomType.findFirst({ where: { id: roomId, propertyId, property: { organizationId } }, include: { ratePlans: true } }); if (!current) throw notFound("اتاق پیدا نشد"); return this.createRoom(propertyId, { name: `${current.name} کپی ${Date.now().toString(36)}`, description: current.description, capacity: current.capacity, bedType: current.bedType, sizeSqm: current.sizeSqm, amenities: Array.isArray(current.amenities) ? current.amenities as string[] : [], images: Array.isArray(current.images) ? current.images as string[] : [] }, actor, organizationId); }
  async createRate(propertyId: string, roomId: string, input: RateInput, actor: AuditActor, organizationId?: string) { return this.prisma.$transaction(async (tx) => { const room = await tx.roomType.findFirst({ where: { id: roomId, propertyId, property: { organizationId } }, include: { property: true } }); if (!room) throw notFound("اتاق پیدا نشد"); const rate = await tx.ratePlan.create({ data: { roomTypeId: roomId, ...input } }); await this.audit(tx, actor, { action: "rate.created", resourceType: "RatePlan", resourceId: rate.id, targetOrganizationId: room.property.organizationId, afterData: { baseRate: rate.baseRate, refundable: rate.refundable } }); return rate; }); }
  async updateRate(propertyId: string, rateId: string, input: Partial<RateInput>, actor: AuditActor, organizationId?: string) { return this.prisma.$transaction(async (tx) => { const current = await tx.ratePlan.findFirst({ where: { id: rateId, roomType: { propertyId, property: { organizationId } } }, include: { roomType: { include: { property: true } } } }); if (!current) throw notFound("نرخ پیدا نشد"); const rate = await tx.ratePlan.update({ where: { id: rateId }, data: input }); await this.audit(tx, actor, { action: "rate.updated", resourceType: "RatePlan", resourceId: rateId, targetOrganizationId: current.roomType.property.organizationId, beforeData: { baseRate: current.baseRate }, afterData: { baseRate: rate.baseRate } }); return rate; }); }
  async bulkInventory(propertyId: string, rateId: string, input: { from: Date; to: Date; weekdays?: number[]; availableRooms?: number; priceOverride?: number | null; closed?: boolean; minimumStay?: number }, actor: AuditActor, organizationId?: string) { return this.prisma.$transaction(async (tx) => { const rate = await tx.ratePlan.findFirst({ where: { id: rateId, roomType: { propertyId, property: { organizationId } } }, include: { roomType: { include: { property: true } } } }); if (!rate) throw notFound("نرخ پیدا نشد"); assertManualInventoryAllowed(rate.roomType.property.sourceType as HotelSourceType); const dates = dateRange(input.from, input.to, input.weekdays); for (const date of dates) await tx.dailyInventory.upsert({ where: { ratePlanId_date: { ratePlanId: rateId, date } }, update: { availableRooms: input.availableRooms, priceOverride: input.priceOverride, closed: input.closed, minimumStay: input.minimumStay }, create: { ratePlanId: rateId, date, availableRooms: input.availableRooms ?? 0, priceOverride: input.priceOverride, closed: input.closed ?? false, minimumStay: input.minimumStay ?? 1 } }); await this.audit(tx, actor, { action: "inventory.bulk.updated", resourceType: "DailyInventory", resourceId: rateId, targetOrganizationId: rate.roomType.property.organizationId, afterData: { from: input.from, to: input.to, weekdays: input.weekdays, affected: dates.length } }); return { affected: dates.length }; }); }
  async inventory(propertyId: string, rateId: string, from: Date, to: Date, organizationId?: string) { const rate = await this.prisma.ratePlan.findFirst({ where: { id: rateId, roomType: { propertyId, property: { organizationId } } }, include: { inventory: { where: { date: { gte: from, lte: to } }, orderBy: { date: "asc" } }, roomType: { include: { property: true } } } }); if (!rate) throw notFound("نرخ پیدا نشد"); return rate; }
  async publicProperties(city?: string) { return this.prisma.property.findMany({ where: { city, publicationStatus: "PUBLISHED", operationalStatus: "ACTIVE", sourceType: { in: ["DIRECT", "DEMO"] }, roomTypes: { some: { status: "ACTIVE", ratePlans: { some: { status: "ACTIVE" } } } } }, include: propertyInclude, orderBy: [{ stars: "desc" }, { name: "asc" }] }); }
  async publicProperty(slug: string) { const property = await this.prisma.property.findFirst({ where: { slug, publicationStatus: "PUBLISHED", operationalStatus: "ACTIVE", sourceType: { in: ["DIRECT", "DEMO"] } }, include: { ...propertyInclude, roomTypes: { where: { status: "ACTIVE" }, include: { ratePlans: { where: { status: "ACTIVE" } } } } } }); if (!property) throw notFound("هتل پیدا نشد"); return property; }
  async bookings(page: PageInput, filters: { from?: Date; to?: Date; status?: string }, organizationId?: string) { const where: Prisma.OrderWhereInput = { serviceType: "hotel", ...(organizationId ? { property: { organizationId } } : {}), relevantDate: filters.from || filters.to ? { gte: filters.from, lt: filters.to } : undefined, bookingStatus: filters.status }; const [items,total]=await Promise.all([this.prisma.order.findMany({where,include:{property:true,roomType:true,ratePlan:true},orderBy:{relevantDate:"asc"},skip:(page.page-1)*page.perPage,take:page.perPage}),this.prisma.order.count({where})]);return{items:items.map(order=>({...order,buyer:undefined,travelers:undefined,guestMobile:maskGuestMobile(order.guestMobile)})),total}; }
  async guests(page: PageInput, organizationId: string) { const where:Prisma.OrderWhereInput={serviceType:"hotel",property:{organizationId}};const[orders,total]=await Promise.all([this.prisma.order.findMany({where,include:{roomType:true},orderBy:{relevantDate:"asc"},skip:(page.page-1)*page.perPage,take:page.perPage}),this.prisma.order.count({where})]);return{total,items:orders.map(order=>{const buyer=order.buyer&&typeof order.buyer==="object"&&!Array.isArray(order.buyer)?order.buyer as Record<string,unknown>:{};return{id:order.id,orderNumber:order.orderNumber,bookingReference:order.externalReference,guestName:`${buyer.firstName??""} ${buyer.lastName??""}`.trim()||"مهمان سفارش",mobile:maskGuestMobile(order.guestMobile),checkIn:order.relevantDate,roomType:order.roomType?.name,status:order.bookingStatus};})}; }
}
